#+title: The Life and Miracles of St. Philomena, 2023 Edition

* Project goal

The goal of this project is to re-typeset and republish the 1865
English version of
/The Life and Miracles of St. Philomena, Virgin and Martyr/.
Modifications to the original text shall be minimal or none, with
exception for corrections.  The ultimate goal of this project is to
prepare this book to travel into the next century or two, to foster
devotion to the dear saint for the greater glory of God.

* What is this?

This book describes the story of St. Philomena, a previously unknown
virgin-martyr, and documents miracles performed through her
intercession.

* Why?

Because the book is from the 1800s (and the body of the martyr was
first discovered in 1802), this book is a primary source of
information on St. Philomena and is worth preserving for that reason
alone.

There is something mysterious and beautiful about St. Philomena which
captivates contemporary audiences.  Her story straddles the boundary
of reality and fantasy.  Yet at the same time, it has received
extensive ecclesiastic approval, so a great deal of effort was spent
verifying the fantastic miracles described.  These fantastic miracles
baffle our prideful post-modern intellects, which do not like to
accept mysteries as facts.  The stories remind us, through the gentle
nudges of the saint, that the universe cannot be reduced to a
collection of mathematical formulae.  There are spirits driving
everything, and God’s fingerprints are everywhere.  (Checkmate,
atheists!)

Today, St. Philomena’s name is rarely spoken outside of rad-trad
Catholic circles, yet she continues to work miracles for those who are
devoted to her.  My hope is to spread devotion to her so that she can
continue to help save souls and to work miracles for the greater glory
of God.

The copyleft CC-BY-SA license was chosen to limit the amount of damage
modern copyright law can do to the dissemination of the book.  I wish
this book to be distributed in a free (as in freedom) manner.  The
copyleft paradigm allows you the reader to become a publisher as long
as you distribute copies under the same CC-BY-SA license.

* Directory

+ orig :: contains a PDF scan of the original book, courtesy of
  Library of Congress, Bertram Smith, and [[https://archive.org/details/lifemiraclesofsa00newy][archive.org]]
+ org :: Emacs org-mode transcriptions of the book’s text (source
  format for later formatting)

* Eventual output formats

The final decisions are in the air at the moment, but it would be nice
to have:

1. Printed books we can distribute, with the Postscript and/or PDF
   published online.
2. HTML copy on the web
3. EPUB?  (For mobile readers)
4. Plain text (least common denominator)

Other things to consider:

+ Appendix with a quick reference of devotions?

* Project status

+ [X] Carefully transcribe the original text (Intro and ch 1-9 done).
  Org mode is the format.
+ [X] Decide on a license
+ [ ] Decide on typesetting path to take: probably TeX/LaTeX
+ [ ] Create a print-friendly format
+ [ ] Create a web-friendly format
+ [ ] Create a mobile-friendly format (so you can take your devotions with you)

* License

The original /The Life and Miracles of St. Philomena/ © 1865
P. O’Shea, Publisher.  The copyright has since expired, and the work
is in the public domain.

/The Life and Miracles of St. Philomena, 2023 Edition/ © 2023 Kyle
Terrien and contributors.

/The Life and Miracles of St. Philomena, 2023 Edition/ is licensed
under a Creative Commons Attribution-ShareAlike 4.0 International
License.

You should have received a copy of the license along with this work.
If not, see <http://creativecommons.org/licenses/by-sa/4.0/>.
