# Fancy typeface needed.

* The Life and Miracles of Saint Philomena, Virgin and Martyr,

#+begin_center
Whose sacred body was lately discovered in the catacombs at Rome, and
from thence transferred to Mugnano, in the Kingdom of Naples.

----------------------------------------------------------------------

Translated from the French.

----------------------------------------------------------------------

“Ye dry bones, hear the word of the Lord.  Thus saith the Lord God to
these bones: Behold, I will send spirit into you, and you shall
live.”---Ezech. xxxvii. 4, 5.

----------------------------------------------------------------------

New York:\\
P. O’Shea, Publisher,\\
104 Bleecker Street.\\
1865.\\

Scanned by the US Library of Congress and distributed by Archive.org.
https://archive.org/details/lifemiraclesofsa00newy

Digitized and republished:\\
Kyle Terrien\\
Friend of St. Philomena\\
2023.
#+end_center

* Approbation.

The present work being extracted from larger works, printed in Italy
with the approbation of the ecclesiastical authority, and having been
examined by theologians worthy of our confidence, we permit the
printing and circulation of it in our diocess, referring, however, on
this matter, to the declarations of the author, and especially to the
decree of Urban VIII.  We believe, moreover, after the example of many
of our colleagues in the episcopacy, that we second the designs of
Divine Providence, by recommending to the faithful of our diocess the
devotion to the blessed Thaumaturga, Philomena, virgin and martyr,
persuaded that it will produce, as it has done elsewhere, the most
abundant fruits of sanctification.

Given at Friburg, in our Episcopal House, the 14th of July, 1834.

*✠ Peter Tobias*,\\
Bishop of Lausanne and Geneva.\\
*J. X. Fontana*,\\
Chancellor of the Bishopric.

* Introduction

The name of the glorious virgin and martyr, Saint Philomena, is not as
well known to the youth of our country as it should be.  From the
beginning of the present century, this saint has been singularly
honored in Italy as the patroness of youth, and the fruits of this
devotion have been truly miraculous.

The present reprint is from an authorized Dublin edition; we had hoped
to have the holy privilege of translating the life of this youthful
saint, but we found others had anticipated us in the pious
undertaking.

The extraordinary devotion of one of the most celebrated personages of
modern times---the Curé d’Ars---to this saint, lends a new and holy
charm to her name, while its amazing fruits show how powerful she is
with God.  His biographer tells us that the curé’s devotion to this
holy virgin and martyr, whom he was accustomed to call his “/dear
little saint/,” was almost chivalrous.  There was the most touching
sympathy between them.  “She granted every thing to his prayers; he
refused nothing to her love.  He set down to her account all the
graces and wonders which contributed to the celebrity of the
pilgrimage of Ars.  It was all her work; he had nothing whatever to do
with it.”  Speaking of this devotion of the curé, Dr. Manning, the
present Archbishop of Westminster, says: “Mysterious and wonderful is
the sympathy which thrills through the communion of saints, unbroken
by distance, undimmed by time, unchilled by death!  ‘The youthful
saint’ went forth from her mother’s arms to die for Christ; the
lictor’s ax cropped the budding lily, and pious hands gathered up and
laid it in the tomb; and so fifteen centuries went by, and none on
earth thought upon the virgin martyr who was following the Lamb
whithersoever He went, till the time came when the Lord would have her
glory to appear; and then He chose a champion for her in the lonely,
toilworn priest, to whom He had given a heart as childlike, and a love
as heroic as her own; and He gave her to be the helpmate of his
labors, and bade her stand by him to shelter his humility behind the
brightness of her glory, lest he should be affrighted at the knowledge
of his own power with God.”

We trust this little volume will serve to enkindle a tender devotion
to the saint in many a young heart.  At the early age of thirteen
years, this true heroine trampled all the vanities of the world under
her feet, and chose to endure multiplied torments rather than renounce
her vow to her crucified Saviour.  What a model of constancy and of
every virtue does she present to us!  Let the youthful heart go to her
when tried, and with unbounded confidence implore her intercession!

Mount St. Vincent,\\
Feast of St. Philomena,\\
August 10th, 1865.

* To the Reader.

This work has been composed at the instance of a venerable prelate.
The greater part of what it contains has been extracted from two
works, written in Italian, on the great saint, of whom it is a
panegyric.  These two works were submitted to the ecclesiastical
authority before publication; and that one, of which I have
principally made use, bears upon it the permission to publish, of the
holy office, under date of December 12, 1833.  The other, of which the
first is but an abridgment, contains this passage: “The name of
St. Philomena is sounded everywhere with glory; devotion to her wins
the hearts of all.  Bishops, archbishops, princes of the Church,[fn:1]
the old, the young, all, even disbelievers, and the very impious,
whose eyes are opened by the works of Thaumaturga, are anxious to
render her homage.  I have heard bishops exclaim, ‘Blessed be God, who
vivifies us through St. Philomena.’”  Since her devotion has been
publicly established in the dioceses, there are seen persons who did
not believe in the creation, seeking with humility an image of the
saint, and as soon as they have obtained it, their faith rejoices, as
if they possessed a treasure.  What mercy God displays in this amiable
saint!  But as Philomena has acquired this celebrity, merely from the
recital of her miracles, communicated orally, or by writing, should we
not see, in this very celebrity, a living proof of the truth of these
wonders?  The graces of every kind with which this proof is
accompanied, form a second testimony, which it is hard to resist.  And
if we add, that the theater of these wonders is Italy; that there, in
presence of the pillar and seat of truth, the orators publish the
prodigies of the saint, and the books whence they draw their
information are printed and reprinted, and that the editions are
quickly exhausted; shall we not, therefore, draw a conclusion
decidedly in favor of what the former preach, and of what the latter
contain?

I shall not, however, here omit to declare, as I am bound to do, and
in accordance with the decree of Urban VIII., that I do not pretend to
give any of the facts contained in this book more authority than the
Catholic, Apostolic, and Roman Church gives or will give to them,
whose decision is, and shall always be, in every thing the rule of my
judgments.

I. F. B. D. L., C. D. I.\\
Friburg, 23d of June, 1834.

* Footnotes

[fn:1] There might be added, the Sovereign Pontiffs themselves, Leo
XII. having proclaimed her the /great Saint/; and Gregory XVI. has
recently blessed one of her images, destined to receive public
devotion, in the capital of Christendom.
