# Fancy typeface needed.

* The Life and Miracles of Saint Philomena, Virgin and Martyr.

----------------------------------------------------------------------

* Introduction

#+begin_quote
/“Qui habet aurem, audiat quid Spiritus dicat
Ecclesiis.”/---(Apoc. ii. 7.)  “He that hath an ear, let him hear what
the Spirit saith to the churches.”
#+end_quote

The different churches or dioceses of which the Christian world is
composed, form but one and the same church: Jesus Christ, our Lord,
the chief; and the Pope, his visible representative on earth, the
common father of all the faithful, governs it in his name and by his
authority.  No one is ignorant of how this church has been formed.
Before ascending into heaven, to be seated at the right hand of his
Father, our Lord Jesus Christ promised his apostles to send them his
Spirit, the spirit of truth, which was to instruct them; the spirit of
fortitude, which was to animate them; the spirit of zeal, which was to
convey them from one end of the world to the other, in order to
proclaim everywhere the divinity of Jesus Christ, “and to call from
the bosom of darkness to the admirable light of the gospel, this
elected race, this royal priesthood, this holy nation, this people
acquired,” for his Heavenly Father and his angels, “by a crucified
God.”---(1 Pet. ii. 9.)

The day of Pentecost arrives---suddenly, towards the third hour, a
great noise is heard, like the blast of an impetuous wind; it fills
the cœnaculum,[fn:1] where the apostles where in prayer with Mary, the
mother of Jesus; and at the same instant there appear, like so many
stars, upon the head of each of them, tongues of fire, the striking
symbol of what the spirit of Jesus Christ wrought in them.

Changed all at once into other men, and become generous combatants for
the faith, they enter the lists, and commence that warfare which has
subjected the whole earth to the empire of the Savior, and which will
terminate but with the end of the world.  “Today,” cries the prince of
the apostles, “is accomplished what was spoken of by the prophet Joel:
And it shall come to pass, in the last days (saith the Lord), I will
pour out of my spirit upon all flesh; and your sons and daughters
shall prophesy, and your young men shall see visions, and your old men
shall dream dreams.  And upon my servants, indeed and upon my
handmaids, I will pour out in those days of my spirit, and they shall
prophesy.  And I will show wonders in the heaven above, and signs on
the earth beneath; blood, and fire, and vapor, and smoke.  The sun
shall be turned into darkness, and the moon into blood, before the
great and manifest day of the Lord come.  And it shall come to pass,
that whosoever shall call upon the name of the Lord shall be
saved.”---(Acts ii. 16, &c.)  What Joel had announced, what Peter
publishes in the middle of Jerusalem, in presence of an immense
multitude, “composed of all the nations which are under heaven”
(ibid.), the history of all the ages of Christianity, even to our own
days, attests the wonderful accomplishment of; so that the Catholic,
Apostolic, and Roman Church can, at the present time, show to the
whole world, as a living title to its veneration, prodigies of every
kind, wrought in every place, by her children; /Domino cooperante, et
sermonen comfirmante sequentibus signis;/ “The Lord working withal,
and confirming the word with signs that followed.”---(Marc. xvi. 20.)

The life-giving Spirit, which has not ceased, and will never cease to
animate it, gives to some, as St. Paul says, the /gift of wisdom/; to
others, the /gift of knowledge/; to one, /the grace of restoring
health to the sick/; to another, a /prophetic knowledge/, that teaches
him to know the future; to others, the /power of working all manner of
prodigies/.---(1 Cor. xii.)  And the end for which this divine Spirit
communicates his omnipotence to the church is, St. Thomas tells us,
“that all men may come to the knowledge of God.”[fn:2]

Here I would be tempted to cry out with the Royal Prophet, “Lord, what
is man, that thou shouldst think of him,” when thou wishest to display
thy glory?  What then is the son of man, that, not satisfied with
visiting him, thou shouldst establish him the depository of thy divine
power, and, as it were, the Lord of his adorable Master?  For, in
miracles, although the creature be not the instrument, he commands,
nevertheless, and God obeys;[fn:3] he wills, sometimes even he
manifests only a desire, and God executes his will, realizes his
wishes; thus St. Thomas expresses it, /Deo ad nutem hominis operante/.
But why should we wonder at favors like these, with which God has been
pleased to honor his church, since, after all, they are the less
precious of his gifts?  “The greatest miracles,” says St. Gregory,
“are those of the spiritual order; those which work not the
resurrection of bodies, but the resurrection of souls.”[fn:4]  “And if
God,” adds St. Augustin, “has placed in reserve, in the treasures of
his mercy, some of these extraordinary effects of his power, which
shake man in his lethargy, and draw from him a tribute of admiration
for his Creator, it is not because he desires him to regard them as
greater than those of which he is every day witness, but in order to
awaken, by what is rare and unusual in them, the value which the
former, by their daily occurrence, had lost, in the minds of
men.”[fn:5]

Thus, though I should see a man, clothed with the divine power as with
a garment, work in heaven and on earth the greatest wonders; though I
should be witness of numberless cures, of resurrections as evident as
multiplied, of the prompt and continual obedience which the elements,
the tempests, all nature would render to the voice of this new
Thaumaturgus, my heart, undoubtedly, humbling itself before God, the
principal author of these prodigies, would render glory to his name,
and would confess the greatness of his power; but it would remember
also what St. Paul said, “That there are graces still more estimable,
because they are better and of a superior order;”[fn:6] and a look of
faith upon the crucifix, and upon the tabernacle where our divine
Saviour resides, would be sufficient to set limit to my admiration,
and make me reserve it for the infinite grandeur of these truly divine
wonders.

I say this, both to answer those who deny miracles, because they
believe them impossible, and to inspire a just admiration in many
others, who, over-desirous of hearing or of seeing these really
admirable works of the Most High, become so fond of them, that every
thing else, no matter how sublime or divine it may be, appears to them
of little value in comparison.  Far be it from us to entertain these
two errors, equally injurious to the goodness of God.  You believe
that he has loved the world to such an excess, that he has given for
it his only Son; you believe that this only Son, the Word of God, God
as his Father, has made himself one of us, that is to say, flesh,
passible and mortal; you believe that he died on an infamous gibbet
for the salvation of men, and that, in order to communicate to them
the merits of his death, he is present and lives in the sacrament of
his church; you believe---shall I say? unhesitatingly---these profound
mysteries, which may be called the miracles of miracles; and those
wonders which the power of God---those works which your senses
themselves attest to you---could you doubt of their possibility?
Leave these doubts to the impious; and when the Lord shows to you, by
his angels and saints, the ordinary ministers of his power upon earth,
that his hand is not withdrawn, and that he is always the God, to whom
it alone belongs to do wonders, reply to all the objections that the
enemy of his glory may suggest to you, these first words of the symbol
of faith, /Credo in Deum Patrem omnipotentem/.

As for the other error, it will be sufficient for banishing it, to
read the words of the angelical doctor.  “The working of miracles,” he
says “has for its end, to confirm in faith.”[fn:7]  How, then, could
it diminish the value of faith?  You ought, on the contrary, as
St. Augustin says, “to aid yourself by these visible works, in order
to raise up your mind to the admiration of an invisible God,” such as
faith shows him to us in his mysteries and in his sacraments.[fn:8]

This is not yet sufficient, adds the same doctor.  “Interrogate the
miracles themselves, to know from them what they wish to tell you of
Jesus Christ; for if you could comprehend them, they have also their
language.”[fn:9]

Do you now, then, believe that they tell anything else, except that
you should ascend still higher, and that the admiration you feel
should give place to the delight with which the super-eminent and
infinite love of Jesus Christ ought to inspire you, in the most
inestimable gifts with which he is pleased to adorn his only and
well-beloved spouse, the Catholic, Apostolic and Roman Church?

After these different considerations, which I have thought it
necessary to place before those who may read this little work, I
approach the subject of which I have proposed to treat.  The object
is, as the title announces, to proclaim a Thaumaturga,[fn:10] whose
wonderful works have made her name celebrated throughout the world.
The abbreviation of the work written on this saint by Don Francis de
Lucia, from which we borrow the materials for this notice, says: “The
greatest miracle, undoubtedly, of all which the Lord has wrought in
favor of the holy martyr, is the astonishing rapidity with which her
veneration has been propagated.  Like the light, that in a few
instants bounds over the measureless space between heaven and earth,
the name of St. Philomena, particularly since the miraculous (and
well-proved) sweat which was seen, in 1823, upon one of her statues,
erected in the church of Mugnano, has reached in a few years to the
ends of the world.  The books that speak of her miracles, the images
representing her, have been carried by zealous missionaries into
China, into Japan, and to several Catholic establishments in America
and in Asia.  In Europe, devotion towards her is extending, not only
in the country and in the villages, but also in the most celebrated
and populous cities.  The great and the humble, the shepherds and
their flocks, unite in doing her honor.  At their head are seen
cardinals, archbishops, bishops, heads of religious orders, and
ecclesiastics, deserving consideration by their dignities, their
learning and virtues.  From the Christian pulpit the most eloquent
orators publish her glory; and all the faithful who know her, in the
kingdom of Naples particularly, and in the neighboring countries,
where there are millions of them, give to her with common accord the
name of the Thaumaturga.  This,” continues the same author, “which we
see, we touch, as it were, with the hand, and which might be called
the most wonderful of the miracles, makes us hope that one day, which
day is perhaps not far distant, the glorious name of St. Philomena
will hold a distinguished place in the Roman Martyrology, and the
universal church will render to her a solemn devotion.”

The hope of the author appears to be well founded.  Already, in 1827,
the keeper of the holy relics, Monsignor Filippo Ludovici, presented
to his holiness Pope Leo XII. a copy of the second edition of the work
of Don Francis de Lucia.  In consequence of what the celebrated
missionary, Don Sauveur Pascali, who was present, said, the Vicar of
Jesus Christ, after running rapidly over the work, and having asked
many questions of Monsignor Ludovici concerning the miracles wrought
through the holy martyr, appeared impressed with a high admiration for
her; and, at the same time, praising God for the power which he had
given her, he blessed, in the most affectionate terms, the persons
who, under the protection of this /great saint/ (these are his words),
consecrated themselves, though in the midst of the world, to the
practice of perfection.

From that time, the number of the devout towards St. Philomena is
daily multiplied in the very centre of Catholicity.  I have myself
witnessed, in 1832, and have seen, with my own eyes, in the pomp
displayed in the /fêtes/[fn:11] celebrated in her honor, persons who
had received from her the most signal favors.  The following are
extracts from two letters written from the same city by a trustworthy
person, the one dated April 4, and the other May 20, 1834:---

“Our St. Philomena does not cease to perform prodigies at Rome, at
Ancona, at Ferrara, at Naples, and at Florence.  In the last-named
city, the Rev. P. F., who was preaching the lent to the court of the
Grand Duke, made the panegyric of the young Thaumaturga.  Her devotion
is extending visibly.  At Caravita we have a superb picture of the
saint; and we shall soon have her chapel.  Every day they make of her
new engravings.”

“The good St. Philomena continues to obtain all sorts of favors for
those who are devout towards her.  To describe here the cures and
other miraculous favors obtained by her intercession, would be to
compose some volumes.  At Rome are seen, exposed in several churches,
her picture and her relics.  The people go in crowds to pay them
veneration; they make prayers of nine days, three days, &c.  Encourage
and propagate devotion to the young Thaumaturga: you will receive from
it, both for yourself and for others, peculiar graces and favors.”

I ought also to add, as I have heard myself in Italy, that a great
number of bishops, both in the kingdom of Naples and the Papal States,
have ordered in their dioceses that a public devotion should be
rendered to the saint, and their clergy say the mass of her and recite
the office.  “It is,” says the above-cited author, “a debt of
gratitude which they have contracted, and which they have desired to
discharge, for the benefits which the saint has bestowed abundantly on
their flocks.”

May this work, then, which I cast, like the last farthing of the
widow, into the treasury of the glorious martyr, draw upon me a look
of her benevolence, and contribute to the propagation of her devotion,
as well as to the manifestation of her power, in the places where her
name and her glory are yet unknown.

* Footnotes

[fn:1] Cœnaculum means literally a room appropriated to eating, and is
particularly used to denote the apartment in which the disciples were
assembled at the time the Holy Ghost descended upon them, and that in
which the last supper was celebrated.---/Transl./

[fn:2] Beneficium commune, quod exhibetur in omnibus miraculis, ut
scilicet homines adducantur ad Dei notitiam.  (2. 2. qu. 178, art. 1
ad 4.)

[fn:3] Obediente Deo voci hominis.  (Jos. x.)

[fn:4] Miracula tantò majora sunt, quantò spiritualia; tantò majora
sunt, quantò per hæc non corpora, sed animæ suscitantur.  (Hom. xxix.)

[fn:5] Ut non majora, sed insolita videndo stuperent, qui hos
quotidiana viluerant, &c., &c.  (Tract. xxiv. in Joan.)

[fn:6] Æmulamini charismata meliora.  Et adhuc excellentiorem viam
vobis demonstrabo.  (1 Cor. xii. 31.)

[fn:7] Operatio miraculorum ordinatur ad fidei confirmationem.
(2. 2. loc. cit. ad 5.)

[fn:8] Hoc admotum sensibus, ut erigeretur mens; ut invisibilem Deum
per visibilia opera miraremur, erecti ad fidem.  (Tract. iv. in Joan.)

[fn:9] Interrogamus ipsa miracula, qui nobis loquantur de Christo;
habent enim si intelligantur linguam suam.  (Tract. iv. in Joan.)

[fn:10] The name which is given to the saints that God renders
celebrated by a great number of miracles.

[fn:11] The word /fête/, taken in its original sense, having become,
from its usefulness, nearly naturalized in our language, the
translator, taking advantage of this circumstance, accordingly gives
to it the meaning it bears in French, viz., as denoting, together with
the English word /feast/, the public rejoicings that take place on
particular and extraordinary occasions, and which generally
distinguish, on the continent, the solemn feasts of the church, and
the annual return of the festivals of Patron Saints.---/Transl./
