* Chapter I. Discovery of the Body of St. Philomena.

#+begin_quote
The Psalmist says: “God is wonderful in His saints.  The God of Israel
is He who will give power and strength to His people.”  Blessed be
God.
#+end_quote

During nearly fifteen centuries, these sacred relics had lain buried
and concealed from the world, when all at once they appear, crowned
with honor and glory.  Whence therefore is this prodigy? who can have
wrought it, but He who dictated these words to His prophet:---/In
memoria æterna erit justus/ (Ps. cxi.): “The just will be in
everlasting remembrance.”

The just, therefore, only deserve to be called wise; since they build
not the edifice of their virtues upon the quicksands of the world, but
upon the imperishable rock, upon “the mountain of God;” /Fundamenta
ejus in montibus sanctis./  (Ps. cxi.)  Oh! that the insensate
inhabitants of the earth could comprehend and appreciate this
language.  But, be as it may, such is the lesson that God has been
pleased to give them: if their folly prevents their profiting by it,
it will not, for all that, be the less truly useful for those who
already walk in the straight way; and, in seeing what the Lord has
done to exalt his humble servant, St. Philomena, they will feel
themselves animated with new ardor, and, full of joy and hope, they
will fly, with the swiftness of the eagle, in the narrow way, of which
the end is life and eternal glory.

The blessed body of St. Philomena was found, in 1802, on the 25th of
May, during one of those annual excavations which are usually made at
Rome, in those places which have been rendered sacred by the burial of
the martyrs.  Those excavations took place this year in the catacombs
of St. Priscilla, on the new /Salarian/ way.  The first thing
discovered was the sepulchral stone, which was remarkable for its
singularity.  It was of baked earth, and distinguished by several
symbols, bearing allusion to virginity and martyrdom.  They were cut
with a transverse line, formed by an inscription, of which the first
and last letters appeared to have been effaced by the instruments of
the workmen, when endeavoring to detach it from the tomb: it was
conceived in these words:---

#+begin_quote
(Fi) Lumena, pax Tecum Fi (At).[fn:1]
#+end_quote

The learned Father Parthenio, S. J., thinks that the two last letters,
Fi, ought to be united to the first word of the inscription, according
to the usage of the ancients, which he says was common to the
Chaldeans, Phœnicians, Arabs, Hebrews; and he adds, there are some
traces of it to be found even among the Greeks.  But the discussions
on this point must be left to the learned, and it will be sufficient
for us to observe, with the same learned Father, that, “on the
sepulchral stones, placed by the Christians upon the tombs of the
martyrs who confessed Jesus Christ in the first persecution, in place
of the formula, /In pace/, generally more used, they put /Pax tecum/,
which is something more lively and more animated.”

The stone having been removed, the sacred relics of the holy martyr
appeared, and close beside, an earthen vase of extremely thin
material, one half of it broken, and the sides incrusted with dried
blood.  The blood, a sure sign of the sort of martyrdom which
terminated the days of St. Philomena, had been, according to the
practice of the primitive Church, collected by pious Christians.  When
the Christians could not themselves perform this office of devotion,
they had recourse to the pagans, and sometimes even to the
executioners of their brethren, in order to have, together with their
venerable remains, their sacred blood, offered so generously to Him,
who, upon the cross, sanctified, by the effusion of His own blood, the
sacrifices, the pains, and the death of His children.

Whilst they were engaged in detaching from the different pieces of the
broken vase the blood that adhered to them, and that with the greatest
care they gathered in a crystal urn the small particles, the persons
present, among whom were some men of talent and cultivated minds, were
astonished in seeing sparkle, all on a sudden, the urn upon which
their eyes were fixed.  They drew nearer; they viewed at leisure the
wonderful phenomenon, and with sentiments of the most lively
admiration, joined to the most profound respect, blessed God, “Who is
glorified in His saints.”  The sacred particles, in falling from the
vase into the urn, were transformed into various precious and shining
bodies; some presenting the luster and color of the purest gold, some
of silver, some appearing like diamonds, rubies, emeralds, and other
precious stones; so that in place of the matter, of which the color,
in detaching it from the vase, was brown and dark, they saw only in
the crystal the mingled brilliancy of different colors, like those
that shine in the rainbow.

The witnesses of this prodigy were not men to doubt of what they had
seen with their eyes, and examined with attention; they knew that God,
particularly to those whom in heaven He loads with the riches of His
glory, is not so sparing of His gifts, as that a like miracle could
cost Him much.  They considered it, not only in itself, as a shadow of
that heavenly brightness promised in the sacred writings to the body
and soul of the just---/Fulgebunt justi sicut sol .... et tanquam
scintillæ/ (Wisd. iii. 7),---but also in the happy and salutary
effects which it produced in their hearts.  They felt their faith
revive, and had they desired to compare the present and the past, they
might have recalled to mind, to justify their pious belief, many
similar facts: that, for example, of St. John Nepomucene, whose body,
having been cast into the Muldau, was distinguished in the midst of
the waters, during the night, by the brilliant light which clothed it
like a garment.  What is told of St. Philomena is certainly more
wonderful, but yet, how far short of that miracle, of which it is the
figure and the pledge, the resurrection of the body, when the elect
shall be transformed into the glory of Jesus Christ!

In reading the foregoing, one must be struck with admiration at the
permanence of this miraculous transformation.  At the present time it
excites the wonder of all who go to venerate the sacred relics.  They
see also, in the same urn, the same brilliant bodies, but their
brilliancy has not always the same liveliness, and the colors with
which they shine have at different moments different shades: at one
time it is the appearance of the ruby, at another that of the emerald
that predominates; again, their brilliancy is at times as it were
tarnished by a light layer of ashes.  Once only it was observed to
disappear, and the terrified eyes of those who witnessed it saw in the
sacred urn but a little ordinary earth.  But this new miracle
terminated as soon as the unworthy eyes of a person, who shortly
afterward died suddenly, had ceased to profane the holiness of the
venerable relics.  O God, how the display of Thy power is at the same
time amiable and terrible!

A difficulty may here present itself to the reader’s mind.  This
prodigy, as we have called it, took place first at the moment of the
extraction of the holy body from the catacombs; the eye-witnesses must
have spoken of it, and consequently it must have made a noise in Rome;
how then has it happened that, from the 25th of May, 1802, until
almost the middle of 1805, an object so worthy of all respect should,
instead of being exposed upon the altars to receive the homage of the
faithful, have been kept concealed and confounded with several other
bodies of holy martyrs, which it had not pleased the Lord to honor in
so singular a manner?  But let us reflect on and admire the wise
slowness, and the supernatural, as it were, circumspection of the
Court of Rome, when called upon to pronounce on these extraordinary
events.  Let us meditate particularly on the views of Providence in
regard to these sacred remains, and the difficulty will disappear.
Yes; God wished, as all that has since happened concurs to prove, that
this new sun, like the morning, after having shed the first light,
should remain some time longer under the clouds.

* Footnotes

[fn:1] “Filumena, peace be with thee, Amen.”
