* Chapter II. History of the Martyrdom of Saint Philomena.

The martyrdom of St. Philomena is known only from the symbols figured
on the sepulchral stone of which we have spoken, and from the
revelations[fn:1] made by the saint herself to different persons.

We shall begin with the figures on the stone: The first is an anchor;
the symbol, not only of strength and hope, but also of a sort of
martyrdom, such as that to which Trajan condemned St. Clement, the
Pope, who, by the orders of this emperor, was cast into the sea, with
an anchor tied to his neck.

The second is an arrow, which, upon the tomb of the martyrs of Jesus
Christ, signifies a torment, similar to that by which Dioclesian tried
to put to death the generous tribune of the first cohort,
St. Sebastian.

The third is a palm, placed almost in the middle of the stone: it is
the sign, and, as it were, the herald of a brilliant victory gained
over the cruelty of the persecuting judges, and the fury of the
executioners.

Underneath is represented a kind of lash, used to scourge criminals,
and which was made of thongs of leather, loaded with lead: with these
the bodies of the innocent Christians ceased to be bruised, only when
they had been deprived of life.[fn:4]

After these are two arrows, so arranged that the first points upward,
and the other in a contrary direction.  The repetition of this may
perhaps mark a repetition of the torments, and its disposition, a
miracle; such, for example, as that which happened at Mount Gargan to
a shepherd, who, having shot an arrow at a bull that had fled into a
cave, dedicated since to St. Michael the Archangel, saw, as well as
several other persons, this same arrow return and fall at his feet.

Lastly, a lily appeared, the symbol of innocence and virginity, which,
with the palm and blood-stained vase already spoken of, proclaims the
two-fold triumph of St. Philomena over the world and the flesh, and
invites the world to honor her, under the glorious titles of Martyr
and Virgin.

We shall now examine whether these revelations agree with the
different marks just mentioned.[fn:5]  The reader will be able to
judge for himself.

The narrative of the artisan is as follows: “I saw,” says he, “the
tyrant Dioclesian desperately in love with the virgin Philomena.  He
condemned her to the many torments, and continued to flatter himself
with the hope that rigor would, in the end, break her courage, and
force her to yield to his wishes.  But seeing that all his hopes were
vain, and that nothing could bend the firm resolution of the holy
martyr, he fell into fits of insanity; and in the madness that then
possessed him, he bewailed his being unable to have her for his wife.
At length, after having tried various tortures (and he cites precisely
the same as were figured on the sepulchral stone, and of which he had
absolutely no knowledge), the tyrant had her beheaded.  Scarcely had
the order been executed, than despair seized his soul.  He was then
heard to cry out, ‘Woe is me!  Philomena will never be my spouse!  She
has been refractory to my will to her last breath; she is dead; how
shall I be able to survive?’ and, on saying these words, he tore his
beard like a madman, and fell into the most frightful convulsions, and
throwing himself from his throne upon the ground, he seized on with
his teeth whatever came in his way, saying that he wished to be
emperor no longer.”  Such, in a few words, is the summary of the
vision with which God was pleased to honor a simple and ignorant man.

The second revelation was made to a very zealous priest, who was
exceedingly devoted to St. Philomena.  Don Francis says that all he
has written concerning it, he has been directly informed of by the
priest himself; and, moreover, that he has heard him relate it in the
very church in which are deposited the holy relics of the saint.  He
thus narrates the manner of his revelation: “I was walking one day in
the country, when I saw approach toward me a woman who was a stranger
to me; she addressed me, saying, ‘Is it really true that you have
exposed in your church a picture of St. Philomena?’  Yes, I answered;
what has been told you is perfectly true.  ‘But,’ added she, ‘what
then do you know about this saint?’  Very little: to this hour we have
only been able to know of her history what may be learned from the
inscription and symbols figured on her tomb; and I set about
explaining them to her.  She suffered me to finish, and then with
vivacity replied, ‘You know nothing more, then?’  No; nothing else.
‘There is, however, a vast deal of other things to be said concerning
this saint.  When they will be known people will be filled with
amazement.  Do you even know the cause of her persecution and
martyrdom?’  Nothing more.  ‘Well, then, I shall tell it you.  It was
for having refused the hand of Dioclesian, who intended her for his
wife; and the motive of her refusal was the vow she had made of
remaining forever a virgin for the love of Jesus Christ.’  At these
words, filled with gladness, like one who had just heard news for
which he had a long time sighed, I said to her, You do not deceive me?
are you quite sure of what I have just heard you say?  But where have
you read this?  For during several years back we have searched for
some author wherein we might find some account of this saint, and our
inquiries have, hitherto, been unavailing.  Tell me in what book you
have found all you have told me.  ‘In what book?’ said she, in a tone
in which was discoverable an expression of indescribable surprise and
gravity.  ‘Is it really to me that such a question should be asked? to
me, as if I could be ignorant of it!  No, surely; I do not deceive
you.  Yes; I know it---I am certain of it---believe me.’  And in
saying these words, I saw her disappear with the rapidity of
lightning.”

To this narrative, faithfully transcribed from the Italian author, I
shall add some of his reflections.  “The stranger,” says he, “(and
whom, in my opinion, it is not difficult to recognize,) speaks of the
hand of Dioclesian as having been offered to her by that prince, which
supposes that the martyrdom of St. Philomena should have taken place
during the time that Dioclesian was a widower, or was on the point of
becoming so by the death of St. Sirena, whom he put to death, together
with his own daughter, in hatred of the faith which both had embraced.
The emperor was then at Rome, where he condemned to death, at two
different times, the heroic St. Sebastian.”  These observations,
suggested by the preceding revelation, help to determine, in some
measure, the epoch of St. Philomena’s martyrdom, and to refute the
objection which certain critics have made, founded upon the long
sojourn of Dioclesian in the east.

The third revelation, and the most circumstantial, is that of a nun of
Naples.[fn:6]  We shall follow the words of the author as closely as
the genius of our language will permit.

“The holy martyr had,” says he, “a long time before given to this
religieuse several distinguishing marks of a very peculiar protection.
She had delivered her from temptations of mistrust and impurity, by
which God had wished to further purify His servant; and to the painful
state in which these attacks of Satan had placed her, St. Philomena
had made succeed the sweetness of joy and peace.  In the intimate
communications which took place at the foot of the cross between these
two spouses of the Saviour, the saint gave her advice full of wisdom;
at one time concerning the guidance of the community, with which this
religieuse had been charged by her superiors; at another time
concerning her own personal conduct.  That upon which they conversed
the oftenest was upon the value of virginity, the means that
St. Philomena had made use of to preserve it unsullied, even in the
midst of the greatest perils; and the immeasurable treasures found in
the cross and in the fruit that it bears.

“These extraordinary favors, granted to a soul so impressed with a
sense of its misery as to consider itself utterly undeserving of them,
made her fear some illusion.  She had recourse to prayer, and to the
prudence of those whom God had given her to guide her conscience; and
while those wise directors submitted to a slow and judicious
examination the different favors with which Heaven had honored this
nun, revelations of another nature were made to her by the
intervention of the same Saint, whose name they all tended to make
more glorious.

“The religieuse, of whom we speak, had in her cell a little statue of
St. Philomena, formed upon the model of her blessed body, such as is
seen at Mugnano; and more than once the entire community had remarked
on the face of this same statue alterations that appeared to them to
be miraculous.  This circumstance had inspired them with the desire of
exposing it in their church with great solemnity.

“The /fête/ took place, and from that time the miraculous statue
remains upon its altar.  The good nun used to go, on the days of her
communion, to return thanks before it; and one day, as she felt in her
heart a great desire to know the precise epoch of the martyrdom of the
saint, that, as she said, those who had devotion to her might honor
her more particularly, all on a sudden her eyes were closed in such a
manner that she was unable to open them, and a voice, full of
sweetness, which appeared to come from where the statue was, addressed
to her these words: ‘My dear sister, it was the tenth of the month of
August that I died in order to live, and that I entered triumphantly
into heaven, where my divine Spouse put me in possession of those
everlasting joys which cannot be comprehended by the understanding of
man.  Thus, it was for this reason that his admirable wisdom so
disposed the circumstances of my translation to Mugnano that, despite
of the plans arranged by the priest who had obtained my mortal
remains, I arrived in that town, not on the fifth, as it had been
intended, but on the tenth of August; and not to be placed with little
public solemnity in the oratory of his house, as he also wished, but
in the church, where they venerate me, and in the midst of universal
acclamations of joy, accompanied by miraculous circumstances which
made the day of my martyrdom a true day of triumph.’

“These words, which carried with them proofs of the truth that had
dictated them, renewed in the heart of the nun her fears lest she
should be under an illusion; she redoubled her prayers, and begged of
her director to undeceive her.  They wrote, therefore, to Don Francis,
enjoining him secrecy on the subject, praying him to answer distinctly
as to the circumstances of the revelation which regarded the
resolutions he had taken.  He answered that they were perfectly in
accordance with the fact.  This reply not only consoled the agitated
nun, but encouraged her directors, for the glory of God and
St. Philomena, to avail of this means which the saint herself seemed
to point out, in order to acquire circumstantial information
concerning her life and martyrdom.

“They therefore commanded this said person to use for this purpose the
most earnest solicitation with the saint, and as obedience, according
to holy writers, is always victorious, one day, when she was in her
cell, in prayer to obtain this favor, her eyes closed as before, in
spite of resistance, and she heard the same voice, which said to her,
‘My dear sister, I am the daughter of a prince who governed a small
state in Greece.  My mother was also of royal blood; and as they were
without children, and they both still idolaters, in order to obtain
some, they used continually to offer to their false gods sacrifices
and prayers.  A doctor from Rome, named Publius, now in Paradise,
lived in the palace in the service of my father; he professed
Christianity.  Seeing the affliction of my parents, and moved at their
blindness, and by the impulse of the Holy Ghost, he spoke to them of
our faith, and even promised them posterity if they consented to
receive baptism.  The grace which accompanied his words enlightened
their understanding, and triumphed over their will; they became
Christians, and obtained the long-desired happiness that Publius had
promised them as the reward of their conversion.  At the moment of my
birth they gave me the name of Lumena, in allusion to the light of
faith, of which I had been, as it were, the fruit; and the day of my
baptism they called me Filumena, or daughter of light (/filia
luminis/), because on that day I was born to the faith.[fn:7]  The
affection which my parents bore me was so great that they would have
me always with them.  It was on this account that they carried me with
them to Rome, in a journey that my father was obliged to make on the
occasion of an unjust war with which he was threatened by the haughty
Dioclesian.  I was then thirteen years old.  Being arrived in the
capital of the world, we three proceeded to the palace of the emperor,
and were admitted to an audience.  As soon as Dioclesian saw me his
eyes were fixed upon me; he appeared to be prepossessed in this manner
during the entire time that my father was stating with animated
feelings every thing that could serve for his defense.  As soon as he
had ceased to speak, the emperor desired him to be no longer
disturbed, but that, banishing all fear, he should think only of
living in happiness.  ‘I shall place at your disposal all the force of
the empire, and shall ask in return only one thing---that is, the hand
of your daughter.’  My father, dazzled with an honor he was far from
expecting, willingly acceded on the spot to the proposal of the
emperor, and when we had returned to our own dwelling, my father and
mother did all they could to induce me to yield to Dioclesian’s
wishes, and to theirs.  What! said I to them, do you wish that for the
love of a man I should break the promise I made two years since to
Jesus Christ?  My virginity belongs to Him, I can no longer dispose of
it.  ‘But you were then too young,’ answered my father, ‘to form such
an engagement,’ and he joined the most terrible threats to the command
that he gave me to accept the hand of Dioclesian.  The grace of my God
rendered me invincible, and my father, not being able to make the
emperor allow of the reasons he alleged, in order to disengage himself
from the promise he had given, was obliged, by his order, to bring me
into his presence.

“I had to withstand for some moments beforehand a new attack from my
father’s anger and affection.  My mother, united her efforts to his,
endeavored to conquer my resolution.  Caresses, threats, every thing
was employed to reduce me to compliance.  At last I saw both of them
fall at my knees, and say to me with tears in their eyes, ‘My child,
have pity on thy father, thy mother, thy country, our subjects.’  No,
no, I answered them: God, and that virginity which I have vowed to
Him, before every thing; before you, before my country!  My kingdom is
heaven.  My words plunged them into despair, and they brought me
before the emperor, who, on his part, did all in his power to win me;
but his promises, his allurements, his threats, were equally useless.
He then got into a violent fit of anger, and, influenced by the devil,
he had me cast into one of the prisons of his palace, where I was
forthwith loaded with chains.  Thinking that pain and shame would
weaken the courage that my divine Spouse inspired me with, he came to
see me every day; and then, after having my chains loosed, that I
might take the small portion of bread and water which I received as
food, he renewed his attacks, some of which, if not for the grace of
God, would have been fatal to purity.  The defeats which he always
experienced were for me the preludes to new tortures; but prayer
supported me; I ceased not to recommend myself to Jesus, and His most
pure Mother.  My captivity had lasted thirty-seven days, when, in the
midst of a heavenly light, I saw Mary holding her divine Son in her
arms.  ‘My daughter,’ said she to me, ‘three days more of prison, and,
after forty days, thou shalt leave this state of pain.’  Such happy
news made my heart beat with joy, but as the Queen of angels had added
that I should quit my prison to sustain, in frightful torments, a
combat far more terrible than those preceding, I passed instantly from
joy to the most cruel anguish; I thought it would kill me.  ‘Have
courage, my child,’ said Mary then to me: ‘art thou unaware of the
love of predilection that I bear to thee?  The name which thou
receivedst in baptism is the pledge of it, by the resemblance which it
has to that of my Son and to mine.  Thou art called Lumena, as thy
Spouse is called Light, Star, Sun; as I myself am called Aurora, Star,
the Moon in the fullness of its brightness, and Sun.  Fear not, I will
aid thee.  Now nature, whose weakness humbles thee, asserts its law;
in the moment of combat, grace will come to lend thee its force, and
thy angel, who was also mine, Gabriel, whose name expresses force,
will come to thy succor: I will recommend thee especially to his care,
as the well-beloved among my children.’  These words of the Queen of
virgins gave me again courage, and the vision disappeared, leaving my
prison filled with a celestial perfume.

“What she had announced to me was soon realized.  Dioclesian,
despairing of bending me, took the resolution of having me publicly
tortured, and the first torment to which he condemned me was to be
scourged.  ‘Since she is not ashamed,’ said he, ‘to prefer, to an
emperor like me, a malefactor, condemned by his own nation to an
infamous death, she deserves that my justice shall treat her as he was
treated.’  He then ordered my clothes to be taken off, and that I
should be tied to a column; and, in the presence of a great number of
gentlemen of his court, he had me beaten with such violence, that my
body, bathed in blood, appeared but one single wound.  The tyrant,
perceiving that I was going to faint and die, had me removed from his
eyes, and dragged again to prison, where he believed I would breathe
out my last sigh.  But he was disappointed, as I was also in the
delightful hope of going quickly to rejoin my Spouse; for two angels,
shining with light, appeared to me, and pouring a health-giving balm
upon my wounds, rendered me more vigorous than I had been before the
torture.  The next morning the emperor was informed of it; he had me
brought into his presence, viewed me with astonishment, and then
sought to persuade me that I owed my cure to the Jupiter whom he
adored.  ‘He desires positively,’ said he, ‘that you should be empress
of Rome.’  And, joining to these seductive words promises of the
greatest honors, and the most flattering caresses, he endeavored to
complete the work of hell which he had begun; but the divine Spirit,
to whom I am indebted for my constancy, filled me at the moment with
so much light and knowledge, that to all the proofs which I gave of
the solidity of our faith, neither Dioclesian nor any of his courtiers
could give any answer whatever.  Then his frenzy came on anew, and he
commanded me to be buried, with an anchor to my neck, in the waters of
the Tiber.  The order was executed, but God permitted that it should
not succeed; for, at the moment in which I was precipitated into the
river, two angels came again to my succor, and, after having cut the
rope that bound me to the anchor, while the anchor fell to the bottom
of the Tiber, where it has remained till the present time, they
transported me gently, in the view of an immense multitude, upon the
banks of the river.  This miracle worked happy effects upon a great
number of spectators, and they were converted to the faith; but
Dioclesian, attributing it to secret magic, had me dragged through the
streets of Rome, and then ordered that I should be shot in a shower of
arrows.  I was stuck all over with them; my blood flowed on all sides;
when he commanded me, exhausted and dying, to be carried back to my
dungeon.  Heaven honored me with a new favor there.  I fell into a
sweet sleep, and I found myself, on awaking, perfectly cured.
Dioclesian learns it.  ‘Well, then,’ he cried, in a fit of rage, ‘let
her be pierced with sharp darts a second time, and let her die in that
torture.’  They hastened to obey him.  The archers bent their bows,
they gathered all their strength; but the arrows refused to second
their intentions.  The emperor was present; he became enraged at the
sight; he called me a magician, and, thinking that the action of fire
could destroy the enchantment, he ordered the darts to be made red in
a furnace, and directed a second time against me.  It was done,
indeed; but these darts, after having gone over a part of the space
which they were to cross to come to me, took quite a contrary
direction, and returned to strike those by whom they had been hurled.
Six of the archers were killed by them, and several among them
renounced paganism, and the people began to render public testimony to
the power of the God that had protected me.  These murmurs and
acclamations made the tyrant fear some more painful accident; he
therefore hastened to terminate my days, by ordering my head to be cut
off[fn:8].  Thus did my soul take flight toward my heavenly Spouse,
who placed me, with the crown of virginity and the palm of martyrdom,
in a distinguished rank among the elect, who partake of the enjoyment
of his divine presence.  The day that was so happy for me, and saw me
enter into glory, was a Friday, and the hour of my death was the third
after mid-day (that is to say, the same hour that saw my divine Master
expire).”

Such is, according to this revelation, the history of the martyrdom of
St. Philomena.  The reader sees in it nothing but what is pious, holy,
and edifying; he finds in it, also, proofs above suspicion of the
truth of the facts which it contains.  He will, perhaps, say to
himself, in thinking of the numerous and brilliant miracles, which
have rendered the name of the holy martyr so celebrated in the world,
that it was becoming that the Lord should manifest, at least
partially, her merits.  The faithful, by this means, are more edified,
and the glory of God, as well as virtue, which He honors in
St. Philomena, is promoted in a great degree.  But since it has not
pleased the divine wisdom to leave, in the historical monuments, any
trace of so great generosity and such heroism, by what other means
than that of revelation could the knowledge of them come to our age?
To our age!  This expression includes many reflections.  It is the age
of pride, it is the age of incredulity, the age in which they desire
to subject to the false lights of a wandering reason the very thoughts
and conduct of God.  For this age, the divine wisdom of Providence, so
admirable in the variety of its combinations, is but folly, a jest; it
turns into ridicule the enlightened simplicity of faith; it treats
every thing of a supernatural order as superstition and fable; it
jests at belief, it despises holiness, it devotes to its hatred those
whom God has charged with its instruction.  The light, nevertheless,
destined to enlighten the world, ceases not to shine.  If those
ungrateful beings are unwilling to profit by it, let them shut their
eyes---that is in their power; although, to say the truth, if they
kept them open to fix them upon the works of God, their countenance
should blush in beholding what His power operates, and what
instruments He uses to display it.  A woman!  An unknown virgin!  All
kinds of wonders wrought through her invocation; wrought in favor of
those whom the world persecutes!  Performed in the bosom of the Roman
Church, whose practices are thus rendered more estimable, its
sacraments more frequented, its ministers more venerable, its name,
faith, and doctrine more clear to its children.  What a humiliation
for them!  And this is the fruit of the world’s secret practices, its
infamous writings, which are become almost as numerous as the sands of
the sea.  I think I see Goliath, struck again by the stone from the
brook, roll expiring at the feet of David, who cuts off his head.  Or
rather, the proud Holofernes, killed in his drunkenness by the weak
hand of a woman: and, while Nabuchodonosor, the image of Satan, as his
general is the image of the vile multitude which Satan directs, grows
pale and shakes upon his throne, at the news of the check which his
invincible army has received, the faithful, figured by the Jews of
Bethulia, make the skies ring with their shouts of thanksgiving and of
victory, and bless with emulation the new Judith, whose powerful arm
has saved them.  God could not choose, in His infinite treasures, a
means more suited than this to confound the pride of the age, and to
give triumph to His cause.

* Footnotes

[fn:1] At the mention of revelations let no one be scared, as it is
certain that, from the beginning of the world, God has revealed to men
many things which were known but to Himself alone.  “He has done so,”
says St. Paul, “in several places, and in many ways, but above all, in
these latter times by His well-beloved Son.”  Then, who will dare to
dispute with Him the right of doing what He has done so often, or
interdict Him the exercise of this right, even in our day?  If the
meanness of man, or his unworthiness, is adduced as an argument
against revelation, is not our God the God of boundless mercy?  Man,
be he ever so miserable, is he not His child, the work of His hands
and of His goodness, destined to live with Him in a blessed eternity?
If it should be objected, that such communications between God and man
are useless, in what manner can this be proved?  The learned and great
Pope Benedict XIV.[fn:2], whose words are of great value in matters of
this kind, did not think so; for he is of opinion that revelations, if
they are “pious, holy, and profitable to the salvation of souls, ought
to be admitted in the process that takes place at Rome, for the
canonization of saints.”  He did not regard, then, all revelations as
useless.  But if, after mature examination---if, after having
consulted persons who are learned and versed in this sort of
matters---if, even, at it has happened with these, after having
submitted them to the ecclesiastical authority, permission has been
obtained to publish them for the glory of our Lord and the edification
of men, who will presume to say that such revelations, filled with
/piety/ and /holiness/, are useless or hurtful?  Let not the believer
merit the reproach of the Holy Spirit that is made to the impious, “of
blaspheming what they know not!”  I do not desire, indeed, to see
imitated the imprudence of those who, at this time particularly, admit
without distinction every thing they hear qualified with the name of
revelation; this would be, I admit, the most dangerous folly.  But I
must repeat with St. Paul, that every revelation, no more than /every
prophecy/, should not be /despised/[fn:3], and that we should yield a
pious belief to those which, according to the rules approved by the
Church and followed by the saints, bear the characters of truth.

Such are the revelations of which I am about speaking in this chapter,
and which are perfectly in accordance with the hieroglyphics traced
upon the sepulchral stone.

[fn:2] /De Beatif. SS./ lib. 3, tom. 7, cap. 3.

[fn:3] /Prophetias nolite spernere./---1 Thess. v. 20.

[fn:4] The discovery of many of the instruments of torture employed to
aggravate the sufferings of the martyrs, has enabled us to have some
idea of what their anguish must have been, when the scourge made use
of was either of leather, loaded with leaden balls, or chains, to the
ends of which metal rings were attached.

[fn:5] It is well to remark, 1st, that these revelations have been
made to three different persons, of whom the first is a young artisan
very well known to Don Francis de Lucia, who, in his work, spread by
thousands of copies in the kingdom of Naples and the surrounding
states, renders public testimony to the purity of his conscience and
to his solid piety.  The second is a zealous priest, now a canon, for
whom the devotion to the holy martyr, of whom he was the perpetual
panegyrist, procured the most singular favors.  The third is one of
those virgins consecrated to God in an austere cloister, about thirty
years of age, and living at Naples.  2d. These three persons were
unknown to each other; they have never had any communication, and
inhabit countries far separated from each other.  3d. The accounts
which they have given, whether by word of mouth or by writing, fully
agree as to the basis and principal circumstances, and in no place
contradict the epitaph which we have just explained, and give to it,
by the details, an elucidation as clear as it is edifying.

[fn:6] This revelation has been published after undergoing a most
strict examination, instituted by ecclesiastical authority, and it
being duly and fully ascertained that it bore all the marks which
distinguish true revelations from false ones.

[fn:7] Don Francis observes that in giving, in the first edition of
his work, this etymology to the name of Philomena, he himself
hesitated to admit it, but that an interior impulse continually urged
him, in spite of his repugnance, not only to write it then, but to
repeat it again in the following editions.  It appeared, indeed, more
natural to take the root of this word from the Greek language, which
gives a different sense, although analogous to the first, and it is
that of /well-beloved/, as the saint is, in fact, particularly so.

[fn:8] “cut off”---The official investigation states her skull was
lanced, not beheaded.  Also, execution by beheading was reserved for
Roman citizens.  (Source pending) (KT, 2022)
