* Chapter III. Translation of the Relics of St. Philomena to Mugnano, and the Miracles That Followed

It has been observed that the body of our saint had remained in
obscurity at Rome till the year 1805.  Divine Providence was pleased
to draw it from that state, and to glorify it in the following
manner:---

Don Francis de Lucia, a zealous and holy missionary of Italy, came
from Naples to Rome with Don Bartholomew of Cesarea, who was chosen by
the Holy See to govern the diocese of Potenza.  He felt an anxious
desire to obtain for his domestic chapel the body of a saint of a
known name,[fn:1] and the Bishop of Potenza having seconded him in the
steps he took for this purpose, he was introduced, shortly after his
arrival, into the apartment where they have collected those blessed
remains, in order that he might himself make his selection.  When he
came into the presence of the bones of the holy martyr, he felt, as he
tells himself, a sudden and quite extraordinary joy, which, showing
itself at the same time upon his countenance, was remarked with
surprise by Monsignor Ponzetti, keeper of the sacred relics.  All his
wishes, from that moment, were for these sacred bones, which he
preferred to all the others, without being able to explain the motive.
He did not venture, however, to manifest his choice, fearing a
refusal, when he was told, on the part of the keeper, that he, having
observed his predilection for St. Philomena, was willing to grant her
to him; and the person added these remarkable words:---“Monsignor is
persuaded that the saint wishes to go to your country, where she will
work great miracles.”

This news filled the soul of the good missionary with consolation, and
he only thought of the means of transferring the holy remains.  They
were to be delivered to him that very day; but as that day, and the
two other following days, passed without seeing the promise fulfilled,
he began to fear lest the keeper would recall his intention.  It was,
indeed, a thing unusual at Rome, to give to a private person an entire
saint’s body, and above all, with a proper name, because at that time
the annual excavations produced very few of this kind, and for this
reason they were only given to bishops or churches.  Monsignor
Ponzetti then informed Don Francis that it was impossible for him to
accede to his wishes, and he offered him his choice among the twelve
bodies without names.

Don Francis found himself, at this intimation, in a great
embarrassment, as well on account of the preparations he had made, the
letters he had written on the subject to Mugnano, and other
circumstances unnecessary to be here mentioned, as also from the
anxiety with which he felt himself oppressed when he attempted to fix
his choice upon another saint.  How admirable is the providence of God
in the secrecy of its ways!  These difficulties, and many others also,
were only to make known more clearly the divine will in regard of the
destination of this blessed body, and to glorify it the more; for
shortly after, without the missionary daring even to think of it, he
became, first, the depository, and then the master of it.

The persons charged with translating the sacred relics of
St. Philomena to Mugnano, set out from Naples toward the evening.
They had counted upon the light of the moon to guide them during the
night, and, therefore, did not provide any other means for lighting
their way, in case of need.  Thus, when a darkness covered the sky,
which threatened to deluge them with rain, they had no protection to
recur to but that of the saint: and God was pleased, for the glory of
His servant, that it should not be sought in vain; for while the pious
escort invoked her with fervor, a column of light was suddenly formed
in the air, the lower part of which rested upon the shrine, where it
remained steadily fixed until daylight, while the upper part of it
reached up to the sky, and showed a certain number of stars, that
appeared to form about it a belt.

The octave day of the translation, during the solemn Mass, in presence
of the crowd which assisted at it, a child, about ten years old, stood
up in the middle of the church, and walked over to the shrine to thank
her benefactress.  Her mother, a poor widow, had carried her in her
arms into the church, and from the beginning of the Mass until the
elevation, the moment of the miracle, had unceasingly and fervently
supplicated the saint.  She joined her voice to those who glorified
God for having conferred such power on St. Philomena.  The child cured
had been a cripple; it could neither walk nor stand; it was known to
all the village, and all the village after Mass saw it walk through
the streets, announcing the miracle of which it had been the object,
and to which they all bore testimony, both in congratulating the
child, and in filling the air with their joyful acclamations.

The miracle wrought during the holy sacrifice attracted such a
concourse to vespers, that the church could not hold all the people: a
great number remained outside, among whom was a woman of the village
of Avella, holding in her arms a little girl, about two years old, who
had been blinded by the small-pox.  The most celebrated physicians of
the capital had been consulted; they considered the disease incurable.
But the afflicted mother, knowing that the things impossible to man
are possible with God, did not despair of the cure of her daughter;
she ran to Mugnano, and although the passage to the saint appeared to
be stopped, for the reason above mentioned, she succeeded in making
her way to the shrine.  Animated, immediately, with a living faith,
she takes some oil from the lamp that burned before St. Philomena; she
anointed with it the eyes of her child, and the little incurable was
instantly cured.  At this miracle there are new cries of joy, and new
emotions produced by exultation and gratitude.  The people outside the
church re-echo the acclamations from within.  The preacher (for all
this took place during the sermon), Don Antonio Vetrano, could no
longer be heard; and as every one was demanding with clamor to see the
child that had been cured, a priest took it in his arms, and mounting
upon a balustrade, he presented it to the view of the people, who,
filled with wonder, proclaimed aloud the power of God and the glory of
His servant.

There took place, during the following days, a great number of similar
miracles, the accounts of which have been published.  We shall now say
a word on the erection of the chapel to the saint.

The first intention of Don Francis was to leave the relics in the
church of our Lady /delle Grazie/.  He destined them, as we said, for
his private oratory.  The numerous miracles, however, worked since
their arrival at Mugnano, showed him that such was not the design of
the Most High.  He resigned himself, therefore, willingly to the
sacrifice which Divine Providence required of him, and occupied
himself henceforward only with the thought of erecting, in that same
church, an altar, where the saint might receive the homage of the
devout.  This altar was shortly after erected.  It was placed in one
of the chapels of the church; but its simplicity corresponded little
with the celebrity of the holy martyr, and the grandeur of the
miracles with which the Lord had been pleased to honor her.  It is not
meant to make any reproach to the people of Mugnano; they were poor,
as well as the most part of those among whom the saint shared her
favors.  Their alms, which were abundant, considering their moderate
means, were scarcely sufficient, particularly during the troubles of
Italy, for the maintenance of the public worship of the saint.  They
could, therefore, only form the desire of seeing the saint’s sanctuary
adorned in a more suitable manner.  God was pleased to second their
pious wishes; and for this end, He made use of one of those
circumstances which are regarded by men as ordinary, but which, in the
mind of God are designed to manifest His glory and to honor His
saints.

A celebrated advocate of Naples, by name Alexander Serio, had, for a
long time, a great devotion toward St. Philomena, and his wife united
with him in this devotion.  As they had considerable estates in the
territory of Mugnano, they came there in 1814, exactly at that time
when each year they celebrated the feast of the Translation.  Don
Serio had been suffering for several years from an internal disease,
which was wasting him away.  His wife, though deeply afflicted, was
still full of hope in the mediation of St. Philomena; she prayed to
her, and got others to offer fervent prayers to obtain the recovery of
her husband.  The day of the /fête/, on which occasion she redoubled
her entreaties, together with her confidence, when she was about to
conclude, after the benediction of the most blessed Sacrament had been
given, Don Alexander, who was in the church with his wife, was
attacked with violent pains in his bowels, which seemed to threaten
his life.  He was quickly carried home, and his disease, in a few
hours, made such a rapid and alarming progress, that his life was
despaired of.  He was unable even to confess himself.  His poor wife,
overpowered with grief, exclaimed, in her deep affliction: “Is this,
then, O St. Philomena, the favor you have obtained for me?” and
immediately, by an inspiration of faith, laying hold of an image of
the saint, she threw it on her dying husband, asking, at least, the
favor of seeing him comforted by the last sacraments before he should
expire.  With this prayer she made a vow: she promised, in the name of
her husband, to have erected in the chapel of St. Philomena an altar
of marble.  At that moment the dying man recovered the use of his
senses.  He declared he was out of danger, confessed himself in an
edifying manner, and as soon as he had finished his confession, he no
longer felt pain, and the usual symptoms of the malady that so long
afflicted him had disappeared.

The favor being granted, the promise was fulfilled; they went even
beyond their engagement; thenceforward, the sanctuary, now so
celebrated, presented to the crowd of pilgrims that visited it a more
consoling sight for their devotion.  There was one thing which
particularly attracted their attention, namely, the great marble slab
that covered the altar, and on which were still visible the marks of a
miracle.  The workman, in using his chisel to fit it into its place,
split it nearly the whole of its breadth.  A number of persons were
present, and it may be imagined what trouble was felt by them and what
confusion by the workman.  He was, notwithstanding this accident, very
expert in his art; and feeling humbled by this awkwardness, he set
himself to mend the breach.  The breach was at the beginning more than
a finger wide; he endeavored to unite the edges by means of a plate of
iron, and then filled the opening with cement.  The /finger of the
saint/, aiding the hand of the workman, by a wonderful miracle, joined
in its former state the marble that had been separated in so
remarkable a manner.  She left merely at the place where it had been
split a line of deep color, which might be taken for a vein in the
stone by a person unacquainted with the miracle.

In 1831, there was at Naples a poor washerwoman, whose state of
pregnancy caused her much suffering.  The name of this poor woman was
Anne Moccia, and her husband’s, Joseph Cagiano.  To obtain some ease
in her sufferings, she resolved to burn, day and night, a lamp before
the image of the saint, and this resolution she kept strictly, as long
as her means enabled her.  But one evening, as she found herself
without oil or money, she thus with simplicity addressed the saint:
“My dear saint, I have nothing for you or for me; here we are both in
the dark; but as I must go to work, let me leave you and say good-by.”
After locking he own and taking the key, she went away to the next
house, that she might work by the light of her neighbor’s lamp.  The
night was far advanced when she returned home.  She opened her door,
and to her great astonishment found the lamp lighting and filled with
oil, and her humble dwelling miraculously illuminated.  She ran
instantly to the window, called her neighbors, and told what had
happened, and invited them to return thanks to St. Philomena for this
feeling act of her goodness, which was the forerunner of several
others.  The good woman, however, appeared not to be better than
before, and her time being come, she had to endure, during five days,
violent pains, which seemed to endanger her life.  The midwife was
certain that the infant was dead for three days past.  The poor
patient got brought to her the image of the saint, and taking it in
her hand, she spoke to her in this manner: “Is this, then, what I have
asked of you? is this the return for the oil I have expended?”  Whilst
she was venting herself in mild complaint, an infant was born, but it
was dead.  The midwife, who expected as much, had sufficient address
to conceal the fact from the mother, and while she bestowed on her all
her care, the little creature remained on the floor, without even
being wrapped up, and this in a very cold season---it was the 13th of
March.  An hour and a half had already passed, when the poor mother
became aware of her misfortune.  In the bitterness of her grief she
was heard to utter these words: “A great favor you have indeed done
me!  Away! I don’t wish you any longer in my house.  Take this image;
put it out of my sight.”  Such expressions may perhaps shock one, but
the living faith that prompted them moved Heaven, and was repaid by a
mighty favor; for at that same moment the infant moved; it cried, and
every one in the house ran toward it, shouting out, “A miracle! a
miracle!”  It was baptized, and after thirty-five days its innocent
soul departed, to join in heaven her who obtained for it the two-fold
life of nature and of grace.  This miracle made a great noise at
Naples; and several learned and pious ecclesiastics published it in
all directions to the honor of the glorious saint.

* Footnotes

[fn:1] The ancient Christians, when so fortunate as to obtain
possession of the mangled remains of the martyrs, frequently buried
them without distinguishing their graves by the empty honor of a name.
This apparent neglect may have arisen from the same cause that leaves
so many graves in /our/ burial-grounds unmarked by a stone.  Besides,
it often happened that criminals, amongst whom Christians were
classed, were sent from the remote provinces of the empire, that their
deaths might afford a sight for that heartless generation.  Indeed, so
little did the Christians esteem the remembrance of the world they
despised, that in /Martyr of Christ/ was comprised all their desire,
their glory, and their hope: hence, in the catacombs, the place
selected for their burial, such inscriptions as the following have
been found:---

#+begin_center
Marcella et Christi Martyres CCCCCL.\\
(Marcella and 550 Martyrs of Christ.)

Hic requiescit Medicus cum pluribus.\\
(Here rests Medicus with many.)

CL Martyres Christi.\\
(150 Martyrs of Christ.)
#+end_center
