* Chapter IV. Miracles Wrought in Favor of Children.

Rose De Lucia, cousin of Don Francis, had a child about eight years
old, which, in spite of the mother’s care and all the efforts of
medicine, had been sinking under a severe sickness: at last he expired
in the sight of his parents and of several other persons.  His poor
mother could scarcely believe her dear child was no more.  She tried
every means to justify a hope that her heart could not quit; but,
finally, every thing proving unavailing, she became aware of the
afflicting certainty that her son was dead; St. Philomena had not
heard the ardent prayers that had been so often addressed to her by a
disconsolate mother.  In the bitterness of her heart, her faith seemed
to revive with increased force.  She ran to the image of the saint,
took it from the wall to which it was hung, and threw it upon the
lifeless body of her child, asking, with loud cries and torrents of
tears, that her son might be restored.  At that moment the corpse
arose, and, as if he had awakened from sleep, he moved to the foot of
his bed; and those eyes that had already wept him dead, beheld him,
not only returned to life without the least symptom of illness, but
vigorous and full of health.

At Monteforte a miracle not less extraordinary took place.  One Lelio
Gesualdo, and his wife, Antonia Valentino, had a little daughter named
Rosa Fortunata, at the time eleven months old: she was their only and
dearly loved child.  One day, somehow or other, this infant escaped
from the hands of the person who carried it, and fell from a window
into the street.  The height of the window was eighty palms (sixty
feet).  The fall must have been rapid, for the head of the child
striking against a brick chimney, detached from it several splinters,
and then fell upon the pavement.  Its mother, who witnessed this
dreadful accident, cried out, “Good St. Philomena, this child belongs
to you if you save her for me!”  The father of the little Rosa, who
was in the street at the same time, made, in his fright, the same
exclamation, and ran to the child, which lay stretched upon the
ground; he took it up, and saw neither wound nor bruise, and there was
on its person no other mark of the fall, than the breaking of a silver
ornament that was about its neck.

Another child, about eleven years old, of the name of Giacomo d’Elia,
son of a surgeon of Visciano, had his foot broken by the wheel of a
carriage that passed over it.  The pain was so great that he became
insensible, and was carried home half dead.  Immediately,
notwithstanding the efforts of art, the wound became gangrenous, and,
on account of the extreme weakness of the boy, amputation being
impracticable, his death was daily expected.  In this state of things
a priest of the place arrived; he had an image of the saint, and
exposed it to the veneration of the family, and recommended them to
interest St. Philomena in their favor.  They knelt down and recited in
common the litany of the Blessed Virgin, and the priest, approaching
the bed of the child, awoke him from his lethargy, and showed him the
image of the saint.  At the sight, young d’Elia began to speak, and
appeared to be no longer ill: the wound was quickly uncovered, when it
was seen that the gangrene had disappeared; the foot was cured, the
child got up, and, although he wanted a toe, he walked with perfect
ease.

The favor that had been obtained by a child not five years old was not
less extraordinary.  This favor might be attributed to the name she
bore.  She was called Philomena, and the saint has always marked a
particular affection for the children who have received this name in
baptism.  The parents of Philomena were Maria Monteforte and Nicolo
Canonico.  One day, as the child was playing near an oven, the door
came off and fell upon her foot, and cut off the fourth toe.  At the
cries of the child they hastened to her relief; they laid her on her
bed, and after examining the hurt, which might become serious, they
called a surgeon, who applied the remedies that his art suggests.
Night came, and the little Philomena could not sleep; but, and she
herself related, and the result proved the truth of her account, while
the whole family were sleeping, the saint appeared to her, gave her
some sweetmeats, saying, “My little Philomena, take courage!  You will
tell your mamma that she must weep no more, and that I will cure you.”
She disappeared.  The child began immediately to cry out, calling its
mother; the mother ran to the child, as well as all the persons in the
house.  Philomena told them in her own way what she had seen, what had
been given her, and what she had been commanded to communicate to her
mother.  This announcement filled the family with gratitude and joy.
They long to see the cure take place.  They saw it realized the next
morning; for she walked about as before, but still wanted the toe that
had been cut off.  It was hoped that the saint would finish the work
she had begun, when they heard that Philomena had received a second
and a third visit, and that caressing her little /protégée/, the saint
had each time bestowed on her some sweet thing.  This hope was not
vain.  Two days before the feast of the saint, Philomena received a
toe in place of the one she had lost.  But it was not the same as the
former one, which had been buried in the church-yard, but another,
proportioned to the rest of the foot, which it was easy to see was
there by some extraordinary operation.

There was another Philomena, somewhat older than the preceding, and
perhaps also more giddy.  Her parents’ names were Tommaso Tedesco and
Ursula Serio.  This event happened in 1830.  The day of
St. Philomena’s feast she was amusing herself by cutting with a pair
of scissors, when, by some awkwardness, she drove them into her right
eye; during five days there issued from the wound blood and water.
The afflicted family had recourse to the intercession of the holy
martyr, but imprudently saying that they would rather see her dead
than blind.  Don Francis, informed of the accident and of the
inconsiderate prayers of the family, goes to them, and after
reproaching them a little, he calls the child, and says to her, “My
dear, go directly to the church; put your finger into the lamp of the
saint, and with the oil that will be on the finger, carefully,
yourself, anoint the wound.”  Philomena obeys, and does exactly as she
had been desired.  The faith of the child obtained her a miraculous
favor: the eye was perfectly cured, contrary to the expectation of the
doctors, who had pronounced it incurable; and besides this, there was
observed something more brilliant in it than the left eye.  Philomena
gathered a still more precious fruit from this prodigy.  Her faith was
so singularly increased, that it merited to be rewarded by another
favor equally wonderful.  Some days afterward she met one of her
cousins whose face had been severely burned by the fire-works on the
day of the /fête/.  She immediately set about persuading him to
imitate her example.  According to her, nothing was more easy than to
be cured; it was only necessary to go and take some oil, and to rub
with it the eye and cheek, and all would be done.  The little boy is
convinced; he goes, and does as his cousin told him, and the next day
in waking he found himself so perfectly cured, that in seeing him, one
would have doubted if anything had happened to him.  Here I would be
tempted to exclaim with our divine Master, “I confess to thee, O
Father, Lord of heaven and earth, because thou hast hid these things
from the wise and prudent, and hast revealed them to little
ones.”---(/Matt/. xi. 25.)  But what is this mystery?  Have we not all
received faith, of which so few, so few, indeed, amongst Christians,
know how to make available the inexhaustible resources!

The poor have also an abundant share in the favors of St. Philomena.
At Vista, a town situated at the foot of Mount Gargano, there lived a
very virtuous, but miserably poor family.  The extreme poverty in
which they were in the country, obliged them to come to town in order
to see if they could gain there a trifle to enable them to subsist.
The husband’s name was Giovanni Troya, and his wife’s Maria Teresa
Bovini.  A ruined cabin, around which was a small garden, formed all
their property and all their hopes.  In this afflicting situation, the
view of the future afforded little consolation; Maria Teresa,
particularly, seeing herself on the eve of giving an infant to the
world, could not think on this subject without feeling her heart
oppressed with grief.  Where can she place her child?  How shall she
procure for it the requisite clothes?  “But God can do all things, and
St. Philomena, if she wishes to aid me, can work a miracle for me.”
In this manner she encouraged herself to bear her affliction, and
often she prayed to the saint not to abandon her in her distress.  At
last the dreaded hour came, and the earnestly-sought relief did not
yet appear.  The embarrassment both of the mother and person who
assisted her was exceedingly great.  Maria Teresa made her complaint
to the saint.  The woman sought everywhere for a bit of linen to cover
the child, for the destitution of this family was such that even a
miserable rag was not to be found.  Moved with compassion, the woman
took a handkerchief from her shoulders and wrapped the child in it,
and the afflicted mother, seeing that there was wanting a band to
swathe the child, said she had one, though half torn and much worn, in
a trunk which she showed.  The woman ran and opened it, but what was
her surprise when she saw there a little bundle of neat and elegant
clothes, arranged with order!  There issued from them so sweet an
odor, that the air was embalmed with it.  She took the treasure and
kissed it; the mother, overpowered with joy, did the same, and was
unable to express her gratitude to her heavenly benefactress.  The
infant, thus richly dressed, was carried to the baptismal font.  The
news of the miracle spread abroad, and persons came from all quarters
to kiss the wonderful clothes, and to breathe the heavenly perfume
they exhaled.  The saint did not stop here.  The next night Maria
Teresa was awakened by the cries of the little child; and by the light
of a dim lamp that lighted the room, she sought for the child, which
she did not find in the place she had laid it.  Doubting and in fear,
she turned to another side, where she beheld a young person dressed in
white, and of a heavenly beauty; who held in her arms the little
child, which she was affectionately caressing.  What a consolation for
the poor mother!  Seized with respect, joy, confusion, and gratitude,
she cannot help exclaiming, “Ah, St. Philomena!”  And St. Philomena
kissed the child and laid it again in its place, and disappeared.
Maria Teresa was, during several days, in a kind of ecstasy from the
effect of this sight; and we who read this, ought we to restrain our
admiration and joy?  Ah! blessed are the simple souls, and the hearts
truly faithful!  Blessed is innocence and poverty, rich in faith!  At
the celebration of the feast of St. Philomena, in 1830, the
magnificence was great and the concourse extraordinary.  All the bells
were in motion; and as children are often fond of going into places
where prudence does not guide them, it happened that a little boy
mounted up to one of the steeples, from which he fell down on the
pavement.  The height of the place from which he fell was about fifty
palms.  His companions thought he was killed; they uttered a shout;
the people ran, and, while expecting to see him dashed to pieces and
lifeless, they saw him, full of vigor, get up and run, and, proud of
his fall, mount up again to the belfry from which he had just tumbled
down.  He owed, he said, his preservation to the name of
St. Philomena, for at the moment of his fall he had invoked her.

On the eve of the same day, a similar miracle took place.  A child,
nine years old, while standing upon a high rock, fell, in the presence
of its parents, into a deep valley which the rock overhung.  Her
parents ran to her succor, and, when they lifted her up, they found
she was insensible and apparently lifeless.  Pierced with the keenest
grief, they threw themselves on their knees, and loudly called on
their blessed protectress, saying, “Blessed Philomena, good Saint
Philomena, do not let us bring our child back dead to the home from
which we have brought her full of life!  Oh! come, we beseech you, to
our relief.”  And in their affliction, to move the heart of the saint,
as a mortification, practiced in that country, they began to rub their
tongues to the rocks, saying they would not cease till their prayer
was granted.  The child, however, did not come to herself; the
appearances were more alarming; in seeing her and touching her you
would have supposed her dead.  The poor parents did not lose
confidence, they cried again to heaven, they imposed on themselves new
mortifications, and at length they had reason to be proud of their
faith and perseverance.  The little girl awoke as if from a deep
sleep; she called her parents, and, while they were running to her,
she got up and went to meet them.  They sought in vain for any mark on
her body, she felt nothing ailed her, the saint had repaired all in
the twinkling of an eye, and the family went on foot to thank her for
the benefit which they owed to her powerful intercession.
