* Chapter V. Favors Granted Through the Intercession of St. Philomena.

One morning, as Don Francis was entering the church to say mass, he
saw his mother run toward him, saying, with an affrighted look, “Give
me a moment; I have something to tell you; I feel myself strongly
urged to tell it to you.”  He desires her to speak; and she began to
recount a vision or dream which she had had on the preceding night.
“I saw,” said she, “St. Philomena preparing for a journey; and,
fearing that she wished to leave us, I was weeping, with many of the
inhabitants of Mugnano, and begged of her to remain with us.  She
then, with the kindest accent, encouraged us, telling us she would
return the next day; but that the family of Terres, to whom she owed
many obligations, being exposed to great peril, gratitude required
that she should go to protect them from it.”  Don Francis regarded
this dream as the effect of the imagination; he could not help,
however, after a little reflection, writing on the subject to the
family of Terres.  They received his letter, opened it, and were
astonished to find in it an event which had like to have destroyed
them the night before.  Robbers, disguised as foreign soldiers, whose
language they borrowed, had come to get lodging, as they said.  As the
door was not opened for them, they began to force it; they threatened
fire and sword; and massacre was about to commence, when an incident,
ordered by Heaven, came to baffle their sanguinary intentions.  The
Terres had no sooner seen themselves in danger, than all the family
implored the succor of St. Philomena.  “No,” said they, “the saint
will not abandon us; let us pray, let us have confidence in her; we
shall be delivered from this danger.”  Their hope was not in vain.  At
the moment that the assassins were rushing toward the staircase, after
having forced in the door, the family heard several voices, which were
well known, call from without, “Light, light!  Quick, quick! bring us
light!”  And these cries, several times repeated, reaching the ears of
the robbers, as well as of the people of the house, encouraged the
latter, and scared the former, and in the twinkling of an eye the
danger was over.  The robbers having taken flight, the Terres saw
their friends come in, both to their joy and the others’ surprise.
The different circumstances of this event appeared to both parties
very singular; but, on the next morning, when the letter arrived, the
mystery was explained.  The family of Terres, and their neighbors,
who, without knowing why, had come to visit so late, discovered in
what had passed the finger of the saint, and thanked her in all the
effusion of their hearts.

St. Philomena comes, not only invisibly, but visibly, to the succor of
those who invoke her.  A wood-cutter of Sirignano, called Carluccio
Napolitano, favored, on account of his devotion toward the saint, with
several graces, had a great confidence in her.  This worthy man
carried always about him one of her portraits, before which he used to
open his heart, in his various necessities.  One time, as he was
journeying, being surprised by the night, he went into an inn.  The
conversation turned on St. Philomena, and he produced his portrait of
her, to show it to the persons present; it pleased one of them, and he
offered two pieces of money for it, another offered three, then four,
five, and even twelve.  But Carluccio answered that he would not give
it for a Roman crown, and that it was too good company for him, and
then he replaced it in his pocketbook.  The next morning he got up
very early, and directed his steps toward a village, called the Sorbo,
where he had to work.  In crossing a thick forest, he went astray, and
soon, not knowing either where he was, or where he was going, his
heart turned to his good saint, to whom he thus spoke: “My dear saint,
yesterday I would not part with you, even for a good sum of money; I
preferred your company to every thing, and to-day you see me astray in
this wood, and you don’t come to my relief!”  He had not finished
these words, when he saw coming a young person, of about thirteen
years of age, dressed in a robe of sky blue, and of great beauty and
modesty.  She looks at him, and says to him, “My good man, what is the
matter with you? what trouble has happened to you?”  Carluccio
explains his embarrassment.  “That is nothing,” she replies; “follow
me, and I will set you again on your road.”  And, without saying more,
she went forward, as if to show him the way.  Walking after her, a
little surprised at the circumstance, he said to himself, “Now, it may
be seen what great goodness St. Philomena has!  She runs to assist
one, when one has scarcely called her; for I cannot doubt but that it
is she that has sent to me this amiable little child.”  He was
occupying himself with these pious thoughts, when the young girl
stopped, and, turning toward him, said, “Follow, now, that road, for
near a mile; you will then meet a woman with a basket on her head; she
is going to the place you seek.  You will go along with her, and
shortly after you will arrive at the place.”  Carluccio thanked her
affectionately, and they separated.  He turned round to see where the
charitable lady was going, but he could see her no longer, and he
continued his way, without further reflection.  Immediately afterward
he found himself in a new difficulty.  The path along which he went
terminated in several others, and which to choose he knew not; lifting
up his eyes, he saw at the same time advancing toward him the woman he
had been told of; he recognized her by the basket.  “Do you know,” he
instantly said to her, “which of these paths leads to the village of
Sorbo?”  “Sorbo!” replies the villager, “I know the way; it is my
village; come and I will bring you to it.”  And he reached the village
shortly after.  It was then that the eyes of Carluccio were opened.
How could this young lady, so genteel, so modest, so elegantly
dressed, be traveling in the wood?  How could she have guessed his
embarrassment, and answered his thought?  How could she foresee what
was to happen to him, and to represent to him so accurately the woman,
the load she was carrying, and the place where she was going?  “No,
no,” said he to himself, “it has not been chance; it is St. Philomena
herself that I have seen, and who has extricated me from the
difficulty I was in.”  During several days, Carluccio seemed almost
beside himself; his heart was filled with a particular love and
devotion toward his celestial guide.

The special court of Avellino, the sentences of which are without
appeal, had condemned to death a man named Pellegrino Ruocco, together
with two other criminals.  The sentence being intimated to the
condemned, preparing them for death was the only occupation of the
persons about them.  The next day, the 19th of August, 1832, the
sentence was to take effect.  Pellegrino had in the town an aunt, who
bore him a great affection.  The mournful news soon reached her, and,
almost as soon, she, together with some other pious persons, fled to
the church, where they offered up fervent prayers for her unhappy
nephew.  A three-days’ devotion was, at the time, celebrating in honor
of the blessed martyr.  After having implored the succor of the Queen
of Virgins, these women, full of faith, went to the altar of
St. Philomena, and asked her, with lamentations mingled with tears, to
vouchsafe to interest herself in obtaining the pardon of the condemned
man.  The crowd that was in the church paying their homage to the
saint, could not refrain, on hearing them, from disapproving of their
conduct.  “Why,” said they, “ask the pardon of a criminal after the
sentence has been passed?  Would it not have been better to have
prayed beforehand?  And what way is there to obtain the pardon?”  It
was in this manner the people reasoned; the good aunt thought
differently.  Persuaded that to the Lord and his saints nothing is
impossible, she returned home, and, prostrate before an image of
St. Philomena, she persevered in asking the pardon of her nephew.  She
thought she heard then an interior voice, which said to her
distinctly, “Go, set out for Naples; cast yourself at the feet of the
king, and the pardon will be granted to you.”  As she did not know
whence this advice could come, she continued her prayer: the more she
prayed, the more she heard the voice; but when she began to see
something supernatural in it, a difficulty started: it appeared to her
that she could never succeed in such an enterprise.  However, the
divine light cleared it up; she decided on the journey; she set out
from Avellino, toward six and three-quarters of the same day, and,
after having run thirty miles, she arrived in the capital toward
midnight.  That same night, her nephew, who had no knowledge of the
project of his aunt, recommended himself ardently to the blessed
martyr; and, having fallen into a slumber, he thought he saw her, and
heard her utter these words: “Fear not; be content: though you should
be at the gibbet, I will know how to rescue you from the hands of your
executioners.”  He awoke, and at the moment he communicated the
favorable dream to his companions.  The next day he told it to the
persons that came to see him; the joy that animated, at the moment,
his countenance, revealed what was passing in his heart; he was
unshaken in his confidence.  His aunt was, however, in a great
embarrassment.  The petition was ready, and the liberty of an audience
obtained; but the king would not be visible until about two o’clock in
the afternoon, and the sentence was to be executed at Avellino, at
five o’clock, the same day.  No matter; God can do every thing.
Already, against all human expectation, the pardon is obtained.  Legal
forms are to be filled up; but if a miracle is requisite to have it
arrive before the execution, St. Philomena is at hand to work it.  It
is impossible not to remark here the attention of God to exalt the
glory of his servant.  He permitted new and almost insurmountable
difficulties to arise; for, in place of expediting at once the pardon,
full two hours were suffered to elapse, and four o’clock struck (there
remained, then, but one hour before the time when the execution should
take place), when the king recollected the pardon, and that it had not
been dispatched.  A new obstacle arose; he had to see the petition; it
could not be found.  He wishes to remember even the names of the three
criminals, for the pardon had been solicited and granted for the
three; but notwithstanding all his efforts, he could only bring to
mind one name, and that was Pellegrino Ruocco.  At once, without any
other formality, he orders one of his officers to carry to the
telegraph the expression of the royal will; but the forgetting the
names causing the forgetting the persons of the others, Pellegrino
Ruocco is the only one of whom he recollects to announce the pardon.
It was time for it to arrive.  Already in Avellino all was in motion
for the execution of the sentence; the criminals, taken from their
prison, were advancing toward the place of execution, and were
arriving at it the moment that the telegraphic dispatch appeared.  It
was an order from the king; the expression of the order was not clear.
It bears but one word: “Let it be suspended.”  The director of the
observatory fluctuates in irresolution.  However, the announcement
concerns the condemned, and there is not a moment to lose.  He leaves
a person in his stead; he goes to the place of execution, and in the
king’s name he commands a delay.  The thing was so extraordinary that
the officer of justice felt great difficulty in acting in accordance
with this order, and they were discussing the matter with warmth, when
the person left at the telegraph ran to them, and brought it in clear
and precise terms the entire pardon.  Pellegrino is pardoned---he
alone.  He had interested in his favor the powerful St. Philomena.
The unhappy man was already upon the ladder; he was informed of his
good fortune; he fell down, overpowered with joy.  He soon recovered;
liberty, honor, life are restored to him, all of which he owes to his
bountiful protectress.  My God, what cannot your goodness do!  And in
us, Christians, what may not the faith do which you have given us!  We
shall give some new examples.

In the month of October, 1832, a violent tempest arose on the Adriatic
Sea, and two fishing barks were wrecking in the very sight of port.
As soon as the news ran through the town of Viesta, crowds flew to the
sea-shore.  The sight was terrific.  Vain efforts were made to convey
succor to the wretched mariners; the fury of the sea allowed none to
reach them; they called, they cried out, their cries rent the hearts
of those that heard them, and they answer them only by fruitless
wishes, sighs, and lamentations.  But the recollection of
St. Philomena suddenly occurs, and revives hope in the despairing
people.  St. Philomena can do every thing with God; she will save from
death the unfortunate that implore her.  A cry is immediately heard on
all sides; the name of St. Philomena echoes in the clouds; a miracle
is wrought.  For some moments afterward the wretched fishermen were
transported upon the shore without their perceiving it, and, together
with their countrymen, they blessed her by whose unseen hand they had
been saved from death.  The prodigy was not, however, so complete that
some fear and bitterness did not remain.  The master of one of the
barks, named Paul d’Aposto, in looking about, missed his two children,
the youngest of whom was but eight years old.  The raging billows had
cast them far from the port.  Some of the people on shore thought they
could see them struggling with the waves, but who could give them any
relief?  She who had just given it with such wonderful success.
“St. Philomena, finish your work; save these two poor children!” was
the prayer that every heart made, and every mouth expressed.  God
willed, for the greater glory of his saint, that the same prayer
should be made by one of the little unfortunates; it was the youngest,
who, remembering in the midst of his danger the miraculous statue of
St. Philomena placed in the church of the Capuchins, had recourse to
her with confidence.  “O new Virgin,” cried he, “who art lately come
to the Capuchins of Viesta, save us; have pity on us.”  And while he
struggled beside his brother against the waves, while his father was
grieving on the shore, and the people, animated with a living
confidence, persevered in their supplications to the saint, behold the
children are saved; they come out of the midst of the foaming sea, and
are safe in the port.  The miracles wrought by the goodness of the
Lord, and the power of his glorified servant, are proclaimed in
acclamations of gratitude and joy.
