* Chapter VI. Examples of a Just Severity Exercised by Saint Philomena Against the Impious.

A man and his wife, who lived at Montemarano, seeing themselves
without posterity, had recourse to St. Philomena, and promised her if
she obtained for them a daughter, to give it in baptism the name of
Philomena, and to carry it immediately to Mugnano, there to return
thanks to the saint.  Their request was granted, and the first
condition fulfilled; but as for the second, in spite of all her
husband could say, his wife would never consent to it.  Two years had
passed away; the infant was handsome and amiable, and her parents
idolized her; but, my God! what a disaster did their infidelity
prepare for them!  The report is circulated at Montemarano that there
is to be a solemn /fête/ in honor of St. Philomena at Castelvetere, a
town a little distance off, and the mother immediately said to her
husband that she would bring there the little Philomena, in order to
accomplish her vow.  He answered that such was not the promise.  “It
is to Mugnano,” said he, “not to Catelvetere, that you should bring
the child.”  “Folly,” replied his wife, “as if there was any
difference between St. Philomena here and at Mugnano!  Let us go
. . .”  She went there, and did not return home until evening,
thinking she had payed her debt.  Heaven judged otherwise, for the
very same evening, at the moment that the little child, full of
health, preparatory to going to bed, had kissed its parents, and
called them in its own little language, they saw it expire in their
arms.  It is useless to trace here their sorrow and their grief.  They
proceeded at last, but too late, to Mugnano, where they related the
tragical event.  “It is,” said they, “certainly our fault.  This last
but terrible blow had been preceded by many warnings, and even
temporal pains, from which we were delivered by renewing our vow.  We
deferred, however, continually, and the patience of the Lord gave way
to his justice.  Oh, may he be satisfied with this afflicting
chastisement!”

A rich man, who had likewise failed to fulfill his obligations, was
punished in a terrible manner.  He suffered from a cancer, which
extended over his face, and had taken away a part of his nose.  As
soon as the blessed relics had arrived at Mugnano, he went to pray and
bemoan his condition before them, promising, if he obtained his cure,
to give to the saint one of the houses that he had.  The miracle took
place at the end of some days, during which he anointed often the
diseased part with the oil of the lamp that burned before the shrine;
not only the sore, but also the shocking deformity which was the
consequence of it, totally disappeared; “and let us admire,” says the
author, an eye-witness of the fact, “this prodigy, doubly miraculous,
inasmuch as the cure contained a sort of creation.”  Every one
expected the speedy fulfillment of the promise.  The cured man, alone,
thought of it no longer.  At the period the chapel was building; its
accomplishment would, therefore, have come in a seasonable time.
Several persons put him in mind of his engagement; they even entreated
his wife; but both answered coldly that it would be time enough after
their death. . . . It appears that God took them at their word;
bankruptcy came upon them, grief soon killed the wife, and her
husband, reduced to the greatest wretchedness, and obliged to pay to
one of his creditors rent for one of his own houses, became attacked
again with the cancer, and it eat away his entire face, and shortly
after deprived him of life.  Happy for him if, before his death, he
acknowledged his fault!

During several years a lawsuit was carried on between two noblemen who
lived at Naples, and a village composed of poor farmers.  The cause of
the latter being the best, justice inclined in their favor, and they
acknowledged that they owed this success more to the protection of
St. Philomena than to the goodness of their cause.  The final sentence
was, however, not yet pronounced, and the two nobles, who were
brothers, by the interest they possessed, and the springs they set in
motion, were so far successful that the suit was decided in their
favor.  The news was almost instantly carried to the little village,
and spread consternation and mourning throughout it.  The suit had
already impoverished its inhabitants, and the loss of it deprived them
of the necessary resources.  What were they to do?  If all hope from
man was extinguished, they had still St. Philomena to look to; they
laid before her, in tears, their case and their hopes.  The noblemen
heard of it, but, supported by the world’s power, they laughed at the
simplicity of the villagers.  “We shall see,” said they to some of
them, “what St. Philomena will do for you.  Wait until we go to you,
and you will tell us what she has availed you.”  Among the villagers
there was a woman who had been particularly favored by St. Philomena;
at these impious expressions she felt greatly hurt, and, transported
with zeal, she exclaimed, “Gentlemen, do not outrage her whom you call
our saint; she is more powerful than you; and woe to him who dares to
provoke her wrath!”  “What then will she do to us?” said they,
laughingly.  “What will she do to you?  She could undoubtedly deprive
you of life even before you set your foot in the village.”  To this
they replied with laughter and expressions of contempt.  The journey
to the village was decided upon, and they departed like two vultures,
about to pounce unerringly upon their prey.  On the way they met
several of the villagers, with whom their malice led them to be merry
at the expense of St. Philomena.  “Very well, very well,” answered
some of the villagers, “justice is on our side, interest and intrigue
on yours.  What could we do, after the loss of our cause, but to have
recourse to our advocate?  Beware of insulting her; she is as much
above us as she is terrible in her vengeance.”  Others, in terms more
bold and clear, merely said, “Gentlemen, no boasting; who knows
whether you will arrive alive in the village?”  These last words were
repeated by several successively, who had neither heard nor seen each
other, and were the foreboding of an approaching catastrophe; they
were, however, replied to by laughter and mocking.  There now remained
but one village to pass before reaching the journey’s end.  The
carriage was near being overturned at approaching this place, at which
one of the brothers said to the other, “What a danger we have just
escaped!  I do not know what might have happened if the carriage had
not recovered its balance.”  The driver heard the observation, but he
to whom it was addressed answered nothing.  The speaker, whom fear had
seized, immediately felt his heart beat in an extraordinary manner, so
that he became too bad to proceed farther, and was obliged to stop at
the village to take some rest.  In a short time he was a corpse,
though but a few hours before enjoying vigorous health.  This terrible
blow made a strong impression on the second, who was of a stouter
constitution than his brother; but who can resist the avenging sword
that arms the saints?  He likewise, an instant after, fell a victim to
the same hand, as he was guilty of the same impiety, and the same
blasphemies.  Thus were realized the prophetic threats of the
oppressed villagers.  They had, notwithstanding, their hearts so good,
that, dissembling the injustice of these unhappy men against them,
after their death they spoke advantageously of their other qualities.
“I saw many of them,” says Don Francis, “come to Mugnano, to recommend
the two deceased to the prayers of St. Philomena.”

The following remarkable example of the punishment of impiety will
conclude for the present the account of the miracles wrought through
the power that God has been pleased, in His mercy, to communicate to
the blessed St. Philomena:---

In a certain neighborhood there lived a very rich and powerful man,
who only used his wealth and interest to harass and persecute every
one about him.  There was no one who had not to complain of his
wickedness; and against every effort that had been made to reduce, by
kindness or force, this little tyrant to his duty, he always found
means to succeed.  St. Philomena had just wrought it in the same place
a miracle, of which all the people and a great number of strangers had
been witness.  This man could not be witness himself, on account of
his absence at the time it took place.  When he returned, he heard the
account; but he instantly exclaimed, “A lie! an imposture!”  One might
have called him a serpent spitting his venom.  “Well,” said the
victims of his injustice, in the simplicity of their faith, “he now
attacks the saint; we are indeed avenged;” and the report spread,
somehow or other, that the unfortunate man would not see the /fête/ of
St. Philomena.  The people all repeated it with one voice.  The thing
happened, in fact, according to the prediction: he died suddenly, “and
his death, which took place before the /fête/,” says our author, “bore
visible and striking marks of a chastisement from Heaven.  But it is
not requisite to render them public.”
