* Chapter VII.[fn:1] Practices of Devotion in Honor of St. Philomena.

The most solid practice, and, perhaps, the least used, of our devotion
toward the saints, is that of which St. Augustin speaks.  “Every time
we honor the martyrs,” says he, “let us not confine ourselves to
asking, through their intercession, temporal benefits; but let us, by
imitating their virtues, render ourselves worthy the enjoyment of
eternal good.  They are truly martyrs who endeavor to follow the
martyrs’ steps; for, could we, in truth, celebrate the glory of their
martyrdom, without feeling ourselves urged to suffer like them?  But,
alas! we wish to share in their joy, without sharing in their
sufferings; and by this means we shall see ourselves excluded from
their happiness.”[fn:2]  These words show us sufficiently the
principal intention of the Lord and of His Church, in the worship we
do to the saints; an intention clearly expressed in these terms by the
eighth General Council, held at Nice:
/Ut nos sanctitudinis eorum fiamus participes/; that we should salute
and venerate the relics of the saints, in order to render us sharers
in their holiness and virtues.

Are we, then, anxious to interest particularly St. Philomena in our
cause?  Let us meditate on her life; let us contemplate her
sufferings; let us reflect on the heroism of her death; and, applying
to our state the virtues which have appeared to us the most important
in her, let us take courage and extirpate from our hearts the vices or
defects opposed to those virtues; let us strengthen, let us perfect
the habit of the same virtues, by the purest and most frequent
exercise of the acts that they produce.

** First Consideration.

Let me reflect, that St. Phiilomena lived in the world, and that I
live in it too; and what is the vast difference between me and her?
She was entirely detached from the world; I am chained to its maxims,
its laws, its impure and ridiculous usages.  Am I not bound to it by
some affection that the Gospel has reproved?  Am I not anxious to
please worldlings---to acquire their esteem?  Do not my desires
impetuously spring towards the seductive and dangerous pleasures which
I see displayed by the vanity of the world?  Ah! let us quit these
bonds; let us abandon these reflections; let us extinguish these
desires, let us aspire to more lasting consolation.  St. Philomena,
help me to honor thee: I wish to offer those sacrifices to God.

** Second Consideration.

St. Philomena lived in the midst of the world; I have the happiness of
being removed from it.  A thousand means of sanctification, which I
have, and of which she was deprived, render to me more easy the
practice of virtue and the shunning of vice.  But what does my
conscience tell me here?  Where does it place me at these reflections?
Can I bear the comparison between myself and the saint?  And, as it
turns out to my disadvantage, what conclusion am I to draw from it?
Ah! Lord, forgive me the abuse of so many graces!  Chastise me not, as
the wicked and idle servant.  I wish to be henceforward faithful and
generous, to employ carefully the numberless ways that Thy divine
bounty affords to me for making satisfaction.

I take this resolution, O St. Philomena, of imitating your example!
Co-operate, I beseech you, by your prayers, in the efforts which I
make.

** Third Consideration.

St Philomena made a vow of virginity, and thus she annihilated the
pleasures of the flesh and hopes that flatter.  The vow absorbed, as
it were, all her earthly futurity; it stripped of its brightest jewel
the royal crown that was destined for her.  “But what matters it?”
said she to herself; “the whole world is nothing compared to the value
of one degree of perfection that I shall give to my soul.  It is
better to belong entirely to God, than to divide our thought, our
cares, between Him and creatures: there is more wisdom in flying from
danger than in walking at the side of the abyss.”  What nobleness in
the sentiment! what liveliness of faith! what generosity in such a
sacrifice!  God calls me, perhaps, on another way.  I say, perhaps;
have I seriously reflected on it?  Ah! if this other way be not the
way of the Lord, but only mine! or the way of interest! or that of an
affection little in accordance with the divine will!  But, in fine, if
I am still a virgin, do I carefully guard this valuable treasure?  So
many enemies, visible and invisible, endeavor to deprive me of it, or
at least to diminish its perfection.  Have I made for it a rampart by
humility, by modesty, by prayer, and frequenting of the sacraments,
&c.?  If I have formed in the world the sacred union of marriage, have
I had for it the respect due to the elevation to which an august
sacrament has raised it, &c.?  O St. Philomena, watch over me from
your height in heaven; watch over the sacred deposit of chastity that
belongs to me.  For your honor I will redouble my watchfulness, &c.,
&c.

** Fourth Consideration.

St. Philomena renounced the most attractive advantages of the
world---she truly comprehended the sense of the words of Solomon,
“Vanity of vanities.”  And not satisfied with comprehending it, she
knew how to reduce it to practice, at the most difficult but most
glorious moment of her life.  My God! what motives for confusion for
me, in this admirable announcement!  Miserable heart, feel shame that
vanity captivates thee, and makes of thee a toy!  By sacrificing all,
St. Philomena became what she is.  By seeking after all, thou hast
deprived thyself of the good things which alone deserved thy esteem.
Thou believest, perhaps, that the world, though poor as it is, has
wherewithal to enrich those who serve it, and that its ignominy (for
has not God cursed it?) can lead you to true honor; that what it calls
pleasures, and what brings to it only bitterness of heart, can bring
to you happiness?  Foolish being! your error is the more culpable,
because it exposes you, with your own consent, to the greatest peril.
For, is it not written, that the friends of the world are the enemies
of God? because the world, with all it possesses, all it is, affords
but only malice.  It is, therefore, full time to undeceive ourselves,
and to use the world as if we used it not---that is, to despise all
that it esteems, to attach ourselves to nothing that it loves.
Forgive, O my God, my past folly!  Help me, O St. Philomena, to
rectify my judgment, to break off my attachments, and even to consent,
cheerfully, to sacrifice every thing, if God should be pleased to
demand so much from me.

** Fifth Consideration.

St. Philomena suffered cruel torments for God: she was young,
delicate, and descended from kings, which according to the world,
exempted her from any kind of suffering; and she had only to conceal
her religion: to do so, no reasons could apparently be more just or
more urgent, the motive being nothing less than to protect her parents
from the rage of Dioclesian, and to save her own life.  But
St. Philomena remembered the express declaration of the Lord:
“Whosoever does not hat his father, mother, and very life for love of
me, cannot be my disciple.”  She, therefore, practiced what she knew,
and suffered long and agonizing tortures.  What do I think of heroism
like hers? have I even the germ of such in my heart?  Perhaps my
obedience to God is because it now costs nothing to nature or the
flesh; hence it is, that as soon as either complain, even against the
most essential precepts, I yield, abandoning the practices of piety
the most serviceable to my soul, and I imagine for myself fantastic
pretexts, which create a delusion, in order to free me from all kind
of remorse.  And can I believe, that by conducting myself in this
manner, I shall come to a happy end?  I cannot believe it; such an end
is impossible.  Our Lord calls those only happy who add practice to
knowledge.  If I am a Christian, I must appear so; and I can neither
be, nor appear to be a Christian, if I do not faithfully follow Jesus
Christ, bearing my cross, as he carried his.  Let us, then, willingly
suffer; let us fulfil our duties, though disagreeable they may be; let
us trample on human considerations; let us show ourselves always, and
in every place, generous and faithful Christians.  I promise to become
so, O my God!  Grant me, I beseech thee, through the merits of
St. Philomena, the grace to accomplish my resolution.

** Sixth Consideration.

St. Philomena remained unshaken under the fiercest tortures,
presenting a prodigy of virtue more admirable, more rare, than the
former.  Many have begun, but many have not persevered to the end.
St. Philomena pursued her course to its termination.  She had no
reflections on self, no considerations on her family, no hesitation on
the brilliant offers the emperor made; she had neither regret,
complaint, nor reproach.  It was the fiat, “Let it be done,” of her
Saviour, in the Garden of Olives; it was that which secured forever
her election and her vocation.  Am I constant to my plans of
sanctification, or am I of the number of those who live an hour for
God, and a day for the world and for themselves?  The Saviour compares
them to reeds shaken by the wind.  St. Paul declares them to be seized
by folly.  The Wise Man likens them to the most changing of all the
stars: /Stultus ut luna mutatur./ “If you persevere not,” says
St. Bernard, “your combats will not be followed by victory;” and
though you were conqueror, the laurel would not decorate your brow.
Ah! my Lord, what shall I answer to thy justice?  A thousand times
have I begun with the spirit, and as often ended with the flesh.  At
one time I have wished to become virtuous, and at another time I have
grown weary of being so.  The moment after I have bid adieu to the
world, I have stretched out to it again my hand; and almost as soon as
I have trampled on its vanities, I have bound myself again in its
chains.  Deplorable inconstancy! worthless desire!  O my God, remove
this changeableness of my inclinations, and fickleness of my thoughts!
St. Philomena, obtain for me perseverance in good, since that only can
save.

** Seventh Consideration.

St. Philomena was powerfully aided by God in her combats, and this is
a proof of what St. Paul says: “God will proportion his succor to the
violence of the temptations, in order that you may resist them.”  And
what was this succor?  Jesus himself---and Jesus in the arms of his
mother---Mary---the holy angels---and the Spirit of Strength, which
descended into the heart of the youthful Philomena.  Thus might she
exclaim with David, “The Lord watches over the preservation of my
spiritual life; before whom shall I tremble?  Though I should see
whole legions united to my executioners, I would still hope.  My God,
you are with me.”  She could then pass, with fearless courage, through
torments, and dare those who inflict them.  O St. Philomena, will not
God do also for me what he did for you?  Am I not his child, like you?
Alas! why should I harbor discouraging doubts?  Why fear being
abandoned?  Has not the Spirit of Truth said, “Blessed is the man who
suffers temptation?”  The same Spirit has put these expressions in the
mouth of St. Paul: “I glory in my sufferings; in putting my fidelity
to trial, they fill me with hope, and hope never deceives.”  Away,
then, with these vain and unjust fears!  In my tribulations I will
call upon my God; in the tempest I will cast in his bosom the sure
anchor of unshaken confidence.  O holy protectress, strengthen me in
these sentiments.

** Eighth Consideration.

St. Philomena withstood victoriously the attacks made upon her, and it
was death upon the field of battle that procured for her eternal
blessedness; a crown more glorious than that of all the princes in the
world; and palms, such as were never gathered by the greatest
conquerors.  She overcame shame and suffering; both united in vain
their efforts to subdue her.  Glory covers her like a garment.  Raise
thy voice, O illustrious martyr! reproach now thy proud enemies; tell
them with the Apostle, “Shame and pain, where now is your victory?
what has become of the sting of your arrows, of the sharpness of your
swords, of the stamp of disgrace and infamy that you attempted to set
on my forehead?  I died, and I live; I conquered, and I triumph; I was
dragged to the scaffold, and now behold me glorified in heaven.”  Thus
humiliation is the forerunner of glory; the cross is the pledge of
happiness.  Have I comprehended it?  Do I wish to come to the practice
of it?  Should I have to support the efforts of the most terrible
enemies, to engage in a combat of blood, how long could it last?  What
sort of a fight would it be?  /Momentaneum et leve/, says St. Paul; a
moment, a slight contest, almost nothing; and then,
/æternum gloriæ pondus/; a weight of glory, but a weight the value of
which measures an eternity!  O my heart, expand thyself at this hope;
not only thou shalt be resigned in thy different trials, but thou
shalt exult with joy at them.  I sow, thou shalt say, but what a
lovely harvest do I secure!  Sceptres and crowns I shall one day
reap.  Let my tears flow, since to them is promised so valuable a
consolation.  Sorrows, avoid me not, as after ye the sweetest joys
will come!  Let me embrace you, O penance, O mortification, as you are
the germ of a glorious resurrection.  Yes, I desire to suffer in order
to enjoy;  I wish to fight in order to conquer.  I wish to humble
myself and to be humbled, that my God may exalt me; I wish to die to
the world, to sin, to myself, that I may live to God, in God, and with
God, for all eternity.  St. Philomena, draw me after you, and aid me
by your intercession, as you have enlightened and animated me by your
example.

** Ninth Consideration.

Saint Philomena appears in the church militant in order to exercise a
glorious apostleship.  The works of the just perish not.  They are
seeds that remain buried for a time, but the comes when they become a
tree, crowned with blossoms and fruit: life is their /winter/, of
which death terminates the chill, that is succeeded by a sun which
will shine through eternity.  The voice that will call the just to the
enjoyment of heaven, will summon them in these words: “Now the winter
is past, the clouds are gone; get up, my friend, and come.”  The just
will spring up at the words, and appear at once among the dwellers of
heaven, like “a vine clothed in leaves and fruit;” like a flower, as
lovely in the brilliancy of its color as in the beauty of its shape;
and the celestial host, on beholding them, will unanimously proclaim,
“A flower has shown itself in our gardens, a new vine sends us its
fragrance; come, come, O holy and dearly beloved soul!” take thy place
in the midst of us; and thus it is the Just One “enters into his
glory.”  But this is not enough; the earth that has sent this present
to heaven, will it have no mark of gratitude?  It shall, and this mark
will be an abundance of new graces, a dew, as it were, of visible and
invisible benedictions.  Let us look for the evidence of this in
St. Philomena.  Are not her merits still living, though many ages have
passed by?  Are they not superabundantly applicable as to astonish the
world?  What hast thou done, O Philomena, to acquire this glory?  “She
loved justice and hated iniquity.”  Her heart, filled with affection
for “the law of God,” was fed with it night and day; and now, as the
tree planted beside the waters, it yields its fruit.  Every thing she
undertakes is crowned with success.  Rejoice, then, O ye just, in the
Lord; praise him when you remember the favors he has bestowed on you,
and of which you have profited so well.  Cannot I form myself after
your example, in order to take part one day in your fruitfulness?  I
will begin, at last to follow you.  I now set about sowing my ground
with acts of virtue; and the more the seed is abundant, the greater
will be the harvest.  Let us draw, then, abundantly out of the
treasures of “piety, patience, charity, obedience,” and of all
Christian virtues.  Let us seek only God in our least actions.  Let us
profit by every grace.  Let us amass, let us treasure up, for the
church of heaven, and the church on earth.  What I do for God, I do
for myself, for the angels, for the saints, for the just, for sinners.
Let us make haste; let us not lose a moment.  Aid me, O St. Philomena,
and you also will share in my harvest.

----------------------------------------------------------------------

* Footnotes

[fn:1] The original source erroneously marks this as “Chapter V.”
---KT

[fn:2] Sermon xlvii., on the Saints.
