* Another Novena to Saint Philomena.[fn:1]

** First Day.

Consider that Saint Philomena was a virgin and always pure, in the
midst of the world, in spite of persecution even to death.  What a
model!  Can I contemplate it without feeling humbled? and knowing the
cause of my confusion, what should be the remedy?

/Practice./---1st. Hear the holy mass in her honor, and visit one of
her statues or images, if such can be done conveniently.  2d. Humble
yourself several times, for whatever, in the course of your life, may
have tarnished the purity of your soul.

** Second Day.

Consider that St. Philomena was constantly pure and innocent, because
she knew how to mortify her inclinations, and to observe in all her
deportment the modesty of Jesus Christ, to keep away from a perverse
world, and from dangerous occasions.  Do you imitate her in this holy
vigilance?

/Practice./---1st. As on the first day.  2d. Avoid what has injured
you; practice what you have neglected, and what will preserve you
always pure and agreeable in the eyes of the Lord.

** Third Day.

Consider that St. Philomena preserved and increased her love of
perfect purity by means of prayer, the abundant source of spiritual
life; by the sacraments, wherein the soul is purified in the blood of
Jesus Christ, and is nourished with his sacred body, the divine germ
of Christian virginity; by the recollection that her members belonged
to Jesus Christ, and that her body was the temple of the Holy Ghost.
Have not you the same means?  What use do you make of them?

/Practice./---1st. As on the first day.  2d. Recite all your prayers
with increased fervor; say to yourself, from time to time: I belong to
Jesus Christ, I am the temple of the Holy Ghost.

** Fourth Day.

Consider that St. Philomena was a martyr, that she had to suffer---to
suffer a great deal, even death itself; and that she displayed in her
torments, invincible patience.  Do you suffer with the like patience?
You have, perhaps, but seldom to suffer; and are never in danger of
death from suffering.  Whence comes so much weakness?  What means will
you take to acquire patience?

/Practice./---1st. As on the first day.  2d. Suffer patiently the few
afflictions, contradictions, and trials, with which the Lord may
please to visit you on this day.

** Fifth Day.

Consider that St. Philomena suffered martyrdom for Jesus Christ:
endeavors were made to deprive her of faith, to make her violate her
baptismal vows, to induce her to follow the example of idolaters or
apostates.  And do not the devil, the world, the flesh, and your own
heart endeavor to lead you into the like sins?

Do not imprudent fears make you fail in your duties, and violate your
sacred engagements?  What shameful pusillanimity!  Let us resume, at
length, courage to perform our duty to God.

/Practice./---1st. As on the first day.  2d. Obtain some victory over
mere human respect: say to yourself, It is better to please God than
men.

** Sixth Day.

Consider that St. Philomena had to put in practice this word of our
Saviour: “He who does not hate his very life for sake of me, cannot be
my disciple.”  She hesitated not to sacrifice all, her very life, for
the love of Christ.  In occasions far less difficult, do we show
ourselves worthy of Jesus Christ?  If there be a competition between
God and man, between grace and nature, between the love of God and
human affections, to which do we give the preference?  Oh, let us
never more degenerate from our dignity of children of God, and of
disciples of Jesus Christ.

/Practice./---1st. As on the first day.  2d. Endeavor to please only
God, or creatures for God alone.  Remove far from you every inordinate
affection.

** Seventh Day.

Consider that St. Philomena in her martyrdom had to suffer raillery,
sarcasm, outrages, and such like painful treatment, from her
persecutors, from her executioners, and from the greater part of the
spectators of her cruel sufferings: she was not, however, the less
generous, the less constant, or less joyful in the public confession
of her faith.  Should the world give you to drink of the cup of
affliction, will you have the courage to drink of it with similar
sentiments?  But what signify contempt, disdain, and even persecutions
the most unjust and bloody?  Can he whom God esteems, can he ever be,
or can he ever think himself dishonored?  Fear not, O Christian heart;
continue your journey, which will end in eternal glory.

/Practice./---1st. As on the first day.  2d. Do not let your heart be
disturbed, if there be said to-day any sharp, rude, or offensive word,
&c.

** Eighth Day.

Consider that St. Philomena, by dying, for our Lord Jesus Christ, to
all things here on earth, entered into the joy of eternal life.  “Yes,
I am certain,” she would say, in her heart, “that the Sovereign Judge
will render unto me, for the perishable goods which I sacrifice to his
love, the crown of justice he has promised me.”  She dies, and
forthwith this worthy spouse of Jesus Christ shines in the tabernacle
of God, with those who accompany the Lamb.  Are these the thoughts
which I entertain when there is question of making any sacrifice for
God?  What impression do they make upon my heart?  To what side do
they make it incline?  The saint says, To have all, let us lose all.
What do I say?

/Practice./---1st. As on the first day.  2d. Impose upon yourself some
voluntary sacrifice.  Perform with promptitude, and with a good heart,
all the duties belonging to your condition of life.

** Ninth Day.

Consider that St. Philomena, for having sacrificed every thing here on
earth for Jesus Christ, receives from him, even in this world, more
than a hundred-fold.  How great is her renown, how powerful her
intercession! how numerous the supplications made through her to the
throne of mercy!  What devout veneration is paid to her statues and
pictures, and what zealous anxiety to obtain her relics!  It is thus
that God accomplishes his promises.  Oh, that we would fulfil, with
equal fidelity, the promises we have made to God!  But by our
infidelity to God, we deprive ourselves of much merit and of many
favors, both for this life and for the next.  Let us take courage.
Let us be faithful to God, and thus be made worthy of the promises of
Christ.

/Practice./---1st. As on the first day.  2d. Do to-day some work of
mercy in honor of St. Philomena.  Prepare yourself, by a good
confession, to receive worthily our Lord Jesus Christ.

** A Prayer in Honor of St. Philomena for Each Day of the Novena.

Glorious Virgin and Martyr, beloved of God, blessed Philomena, I
heartily rejoice and give God thanks, that he has given you so much
power, for the glory of his name, for the edification of his church,
and to honor the merits of your life and of your death.  I am happy to
see you so great, so pure, so generous, so faithful to Jesus Christ,
and to the precepts and counsels of his gospel, and so highly rewarded
both in heaven and on earth.  Attracted by your example to the
practice of sterling virtues, full of hopes at the view of the rewards
bestowed upon your merits, I purpose to follow you in the avoidance of
all evil, and in the fulfilment of God’s commandments.  Assist me, O
glorious saint, by your powerful intercession, and obtain especially
for me, a perfect purity, a fortitude invincible in all sorts of
attacks, a generosity which refuses not to God any thing whatsoever,
and a love, stronger than death, for the faith of Jesus Christ, a
ready and willing obedience to the holy Roman Catholic Church, and to
our Sovereign Pontiff, the common father of all the faithful, the
pastor of pastors and of their flocks, and vicegerent of Jesus Christ
throughout the universe.

To these favors which I have now asked through your intercession, O
blessed Philomena, I also ask other new graces, which I have the
fullest confidence to obtain through your powerful intercession.
/(Here declare those graces to the saint with simplicity, confidence,
and humility.)/  Surely God, who is so good, and for whom you have
given up your life; God, who is so good, and who has bestowed so many
gifts and favors, both upon you, and through you; this God, who is so
good as to have died for me, and to give himself to me in the
eucharistic form, surely he will not refuse to attend graciously to
your prayers, to my entreaties, and even to that necessity, which he
himself, in some sort, feels to do us good.  Thus, I hope; I put all
my confidence in God and in you.  Amen.

O Jesus, grant me grace to love thee, and to make others love thee.  O
Mary, my tender mother, obtain for us a great love for Jesus Christ.

* Footnotes

[fn:1] This Novena is usually made from the 1st to the 10th of August,
which is the day of the martyrdom and translation of the Saint; but it
may be said at any other time.
