* Prayers in Honor of St. Philomena, Virgin and Martyr,

#+begin_center
To implore her powerful protection in the tribulations, the
temptations, and in all the necessities of life.
#+end_center

# There is no “real” way to typeset subtitles in org-mode.  ---KT

** For Sunday.

O most blessed St. Philomena! the /Thaumaturga/ of our age, behold me
prostrate before that throne, upon which the most adorable Trinity has
placed and crowned you with the double crown of virginity and
martyrdom.  I raise my hands in supplication to you.  What a glorious
spectacle in constancy and strength did you not present, before
heaven, and to earth, to angles and men, at the time that the tyrants
of the world persecuted the sheep of the Saviour, and deluged the
church with their blood!  The heavy anchor tied to your neck, even the
waters into which you were cast, shook not for an instant the fidelity
you had sworn to your heavenly Spouse.  The merciless hand of the
executioner rending, with its murderous lash, your virginal flesh,
from which your pure blood gushed forth, extorted from you neither a
tear nor a sigh.  The arrows, the chains, the sword that perfected
your sacrifice, and placed your sweet soul in the possession of glory,
were unable to abate, even for a moment, the ardor of your generous
heart, for your Divine Lover.  Now, the Lord, in recompense of your
anguish for the glory of that lily that you preserved inviolate,
amidst the thorns of the world, and to the confusion of this
corrupted, has vouchsafed to glorify you, by the power of your
intercession.  From the east to the west, from the north to the south,
the fame of your wonders is heard; the people crowd to seek refuge
under the wings of your protection.

It is therefore to you, O illustrious martyr, it is to you that I have
recourse; I stretch out to you my suppliant hands.  Ah! from the
height of the celestial country, vouchsafe to cast a look upon me,
your humble servant.  O pure virgin!  O Holy martyr, Philomena,
comfort me in my afflictions; strengthen me in temptations; preserve
me in persecutions; aid me in all dangers; but above all, aid me at
the terrible hour of death, when I shall have to fight with all the
powers of hell, and when a dreadful moment shall decide my eternity.
In these days of darkness protect the church, which the impious attack
with open force; baffle the designs of the wicket, and maintain the
faithful in the unity of the Catholic Church.  Amen.

** For Monday.

Most pure virgin, most faithful disciple of the Gospel, and invincible
martyr of Jesus Christ, whom God adorned with so many graces, with
purity; who were enriched with so lively a faith, and such singular
force, in the very midst of an infidel and corrupted world, and
particularly at Rome, at the time the centre of idolatry, of tyranny,
of infernal superstition, and the school of the most enormous vices; O
blessed Philomena, who at this pagan and corrupted head of the world,
preserved for yourself an unshaken faith and inviolable purity to your
last breath, sacrificing to your Spouse, in the most painful
sufferings, your life, we beseech you, by the distinction of your
merits, to obtain for us, at the merciful throne of our heavenly
Father, the gift of perseverance in faith, of purity of mind and body,
and a holy death in the grace of Jesus Christ.  Amen.

** For Tuesday.

O courageous martyr and most faithful virgin of Jesus Christ! to
preserve unsullied the treasure of purity and of faith in your God,
you suffered yourself to be cast, with an anchor tied to your neck,
into the waters of the Tiber, from which your heavenly Spouse
delivered you unhurt; we claim your intercession, to the end, that in
the midst of the waters of bitterness, of anxieties, and of
tribulations, which unceasingly surround us, we may be supported with
strength, and preserved from the shipwreck of our sins, and from the
death of our souls; and that we may not be sunk by the waters of
temptation.  Amen.

** For Wednesday.

O beloved spouse and fearless martyr of Jesus Christ! to preserve your
virginity, your heroic faith made you endure with constancy,
ignominious sufferings in the presence of a great number of vicious
pagans, in the streets of idolatrous Rome.  Besides, for the glory of
virginity, and of the evangelical doctrine, you renounced the
pleasures of the flesh, the delights and pomp of the world, and even
the life of your chaste body.  You suffered also the cruel scourging
with iron-loaded lashes, which, in covering you with wounds, made you
resemble that Jesus whom you so ardently loved.  Alas! we confess
ourselves wretched sinners, sensual and delicate worldlings; obtain
for us the strength to enable us to live far removed from the mire of
sin, and to die with courage, like you, in the faith of the Roman
Church, though to do so should cost us suffering, disgrace, and even
life itself.  Amen.

** For Thursday.

O courageous Virgin! who, with a supernatural joy and invincible
force, thrice sacrificed your virginal body, in order to persevere in
the doctrine of Christ, and defended heroically your virginity and
faith; who esteemed yourself happy to be three times pierced with
darts; who received as many palms and crowns as your body did wounds,
for your heavenly Spouse, pray for us, who observe so indifferently
the law of God; obtain for us the strength necessary to come to
eternal salvation, to the end that we may bear with resignation the
pains, the sorrows of this life, and that we may resist all the
attacks of hell.  Amen.

** For Friday.

Illustrious martyr, and glorious spouse of Jesus Christ, who, being
God and Saviour, permitted you not to be overcome, but having designed
for you a distinguishing crown, prolonged your life, which,
multiplying your sufferings, afforded the means of adding to your
laurels and triumphs, and rendered you more admirable in the eyes of
the celestial spirits, and more exalted amongst the glorious martyrs.
By the divine counsel you were loaded anew with chains, and carried
before the tribunal of the tyrants of Rome; your angelic purity and
holy faith were put to new trials, and your barbarous enemies,
despairing of conquering the heroic firmness of your heart, condemned
you to be beheaded---your final suffering, which, by filling up the
measure of your merits, introduced you triumphant and glorious into
the kingdom of your Spouse.  Amen.

** For Saturday.

We beseech you, O great saint, to cast upon us a look of charity.
Vouchsafe to show us, by some mark of your goodness, that our humble
homage has been grateful to you.  Obtain for us the graces we desire
for our salvation, as well as those which you see we require, in order
to be delivered from the eternal death we have so often deserved.
Grant that, in this hope, we may be freed from all troubles, that is,
that your sweet charity may animate and console us.  We bless with our
whole heart, and with the most profound adoration, the most Holy
Trinity, for having loaded you with so many benedictions of earth, for
having adorned you with so much purity, with faith and with strength
for having exalted you to such high sanctity, and for having supported
you in the midst of your enemies, and of such horrible sufferings, and
conducted you in triumph to glory in heaven.  We give thanks to the
most pure Virgin Mary, Mother of God, Queen of Martyrs, who, like a
tender mother, comforted you by her powerful protection in the midst
of your torments.  We hope, O holy martyr, that you yourself will
protect us, now that we honor your merits and your glorious triumph.
Amen.
