* Litany in Honor of Saint Philomena.

#+begin_verse
Lord, have mercy on us.
Christ, have mercy on us.
Lord, have mercy on us.
Christ, hear us.
Christ, graciously hear us.
God the Father, of heaven, have mercy on us.
God the Son, Redeemer of the world, have mercy on us.
God the Holy Ghost, have mercy on us.
Holy Trinity, have mercy on us.
Holy Mary, Queen of Martyrs,[fn:1]
St. Philomena, child of benediction,
St. Philomena, who wast the daughter of light,
St. Philomena, who from thy childhood chose Jesus Christ for thy spouse,
St. Philomena, who despisedst, with heroical courage, the greatest honors, in order to continue faithful to Jesus Christ,
St. Philomena, whose faith and love for Jesus Christ promises and threats could not change,
St. Philomena, whose constancy, neither the entreaties of a father, nor the tenderness of a mother could diminish,
St. Philomena, who, for thy great love of God in sufferings, deservedst to be consoled by Jesus and Mary,
St. Philomena, whose eagerness to endure new torments daily increased,
St. Philomena, whom God intrusted to the guardianship of angels, and who, by their aid, many times overcamest the fury of thy persecutors,
St. Philomena, whose glory God has been pleased to manifest by continual miracles,
St. Philomena, who sufferedst many kinds of martyrdom in the various torments thou hadst to endure,
St. Philomena, whose example attracted many to the faith,
St. Philomena, who, like Jesus, wast bound to a pillar and scourged,
St. Philomena, perfect model of Christian virgins,
St. Philomena, who protectest in a particular manner those who honor thee,
St. Philomena, whom the church honors and reveres as an illustrious virgin and martyr of Jesus Christ,
St. Philomena, who enjoyest a neverending glory,
Lamb of God, who bearest away the sins of the world, forgive us, O Lord.
Lamb of God, who bearest away the sins of the world, graciously hear us, O Lord.
Lamb of God, who bearest away the sins of the world, have mercy on us, O Lord.
#+end_verse

** Prayer.

O glorious virgin and martyr, whose glory God has been pleased to make
known by singular miracles, we address ourselves to thee with entire
confidence.  Obtain for us, that, by thy example, we may fight
courageously against whatever is opposed to the reign of Jesus Christ
in our hearts; that we may adorn them with virtue like thine, with
that angelical purity, of which thou art a perfect model; and that,
inflamed with the love of Jesus, we may continually walk in the way
which he has marked out, to the end that we may one day partake of thy
everlasting happiness, through our Lord Jesus Christ, who, with the
Father and the Holy Ghost, liveth and reigneth one God, in perfect
Trinity, for ever and ever.  Amen.

** The End.

* Footnotes

[fn:1] Pray for us.

# There is no way to do fancy graphics in this layer of the process.
